-- Elimina tabela
drop table palestrantes;

-- Cria tabela
create table palestrantes(
	nome varchar(200),
	foto varchar(1000),
	localizacao varchar(200)
);

-- Populando Banco
INSERT INTO PALESTRANTES VALUES('Adriana Antunes','./Mulheres Palestrantes_files/tumblr_n8g0ld4jND1tfojqwo1_1280.jpg','Caxias do Sul/RS');
INSERT INTO PALESTRANTES VALUES('Adriana da Rosa Amaral','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAqwAAAAJDE0YmE0MmIxLWM5NjMtNDQ5MC05M2FjLWNjMDFjOGU5NzA1Zg.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Alda Rocha','./Mulheres Palestrantes_files/07ac697bcff40050a82cb4503de9eb68.png','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Alessandra Guglieri','./Mulheres Palestrantes_files/0ccfeff.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Alice Coutinho','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Aline de Campos','./Mulheres Palestrantes_files/AlinedeCampos.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Aline M. C. Freitas','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAYFAAAAJDVkMzNjY2U2LTNjMGQtNDE5NC1hNDgxLTBmM2RhY2MyYjBiNQ.jpg','Belém/PA');
INSERT INTO PALESTRANTES VALUES('Aline Pêgas','./Mulheres Palestrantes_files/profile.jpg','Curitiba/PR');
INSERT INTO PALESTRANTES VALUES('Alline Jajah','./Mulheres Palestrantes_files/allinejajah-1418015868_280.jpg','Goiânia/GO');
INSERT INTO PALESTRANTES VALUES('Alline Oliveira','./Mulheres Palestrantes_files/26e9188.jpg','São Paulo/SP, Rio de Janeiro/RJ, Brasília/DF e Goiânia/GO');
INSERT INTO PALESTRANTES VALUES('Alynne Cid','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAcsAAAAJDc5ODNjOTU3LWE5MjItNGZjNi04ZjJkLTYwODJlYjU3OWYyNw.jpg','Belém/PA');
INSERT INTO PALESTRANTES VALUES('Amanda Santana','./Mulheres Palestrantes_files/b1888a06cb886303500bc65c1d81f200.jpeg','Aracaju/SE');
INSERT INTO PALESTRANTES VALUES('Amanda Silva Vieira','./Mulheres Palestrantes_files/ff491a846bf9e5f3f5d081787ff54ae2.jpeg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Amanda Vilela','./Mulheres Palestrantes_files/3ab1d4a265ad9289afe10956a78271df.jpeg','Sorocaba/SP');
INSERT INTO PALESTRANTES VALUES('Amanda Zacarias Marinho','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAigAAAAJDc4Y2E4ZjUyLTVhYzAtNDgxNi05YTk0LWZhY2M5OWQ1Y2MzNA.jpg','Belo Horizonte/MG');
INSERT INTO PALESTRANTES VALUES('Amélia Pessoa','./Mulheres Palestrantes_files/9038852','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Ana Antar','./Mulheres Palestrantes_files/ts6SYp9G_400x400.jpg','Salvador/BA');
INSERT INTO PALESTRANTES VALUES('Ana Barcellos','./Mulheres Palestrantes_files/8314551','Brasília/DF');
INSERT INTO PALESTRANTES VALUES('Ana Carolina Alves Rodrigues','./Mulheres Palestrantes_files/0b16903eeb7899542ce526c21eee7c74.jpeg','Florianópolis/SC');
INSERT INTO PALESTRANTES VALUES('Ana Clarissa','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAMDAAAAJDRiZDJjMDczLWE5MWMtNGU0Yi04ZTc4LTk5NjU2M2VmNTlmNQ.jpg','Manaus/AM');
INSERT INTO PALESTRANTES VALUES('Ana Del Mar','./Mulheres Palestrantes_files/0_pIHHOU-J17PpZDyH.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Ana Fontes','./Mulheres Palestrantes_files/AAIAAgDGAAAAAQAAAAAAAAmTAAAAJDY4MGJhMGI5LTBhNmEtNDU4Yi04ZWVlLWE1ZjFhNzdlODNmZg.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Ana Julia Ghirello','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAhkAAAAJDc3MjI1MDk3LWFiMDctNDNlYi1iYmJhLTEwYjA3NTBkNGVmOA.jpg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Ana Luíza Avellar','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAgUAAAAJGI2MjVlZjQwLTQzMzAtNDE3Zi1hZGQ1LWRmZGI5NmEzNzE1NA.jpg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Ana Luiza Bastos','./Mulheres Palestrantes_files/10088900','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Ana Paula Coelho Barbosa','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAi8AAAAJGM4ZDM3NDk0LTcxNmEtNDBjYy1hODFlLWQ0Yzg0ZmViMjUxMA.jpg','Ilhabela/SP');
INSERT INTO PALESTRANTES VALUES('Ana Paula da Silva Mendes','./Mulheres Palestrantes_files/27858278_2471054366452191_7904831545054840493_n.jpg','Teresina/PI');
INSERT INTO PALESTRANTES VALUES('Ana Paula de Luca','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Ana Paula Gaspar','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Ana Paula Gomes','./Mulheres Palestrantes_files/38e1ead1b5834e26fb681116e6b7ebf5.jpeg','Belo Horizonte/MG');
INSERT INTO PALESTRANTES VALUES('Ana Paula Marques','./Mulheres Palestrantes_files/placeholder-female.jpg','Sobral/CE');
INSERT INTO PALESTRANTES VALUES('Ana Paula Vargas Maia','./Mulheres Palestrantes_files/AAIAAgDGAAAAAQAAAAAAAAxkAAAAJGJmYTRmMzUzLWYzYjYtNDQ2ZS04MWM3LTAxMjIxZTVhMGJlOA.jpg','Salvador/BA');
INSERT INTO PALESTRANTES VALUES('Ana Raquel Calháu Pereira','./Mulheres Palestrantes_files/5718645','Itajubá/MG');
INSERT INTO PALESTRANTES VALUES('Ana Ribeiro','./Mulheres Palestrantes_files/fbcae7dfc50e5e33d18cae175d957c64.jpeg','Campina Grande/PB');
INSERT INTO PALESTRANTES VALUES('Ana Rute Mendes','./Mulheres Palestrantes_files/a4d2fe468c774392ea7deb9efb9e61f5.jpeg','São Paulo e Campinas/SP');
INSERT INTO PALESTRANTES VALUES('Ana Schwendler','./Mulheres Palestrantes_files/I8PSmdIN.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Ananda Carvalho','./Mulheres Palestrantes_files/3c368abae57d0fb60ff976fb1be47d99','Manaus/AM');
INSERT INTO PALESTRANTES VALUES('Andrea Barberà','./Mulheres Palestrantes_files/AAIA_wDGAAAAAQAAAAAAAAquAAAAJDMzZTZlOTE4LWZmNTctNDUwMy05NzExLTI3ODQ2MDM1M2ExNg.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Andrea Siqueira','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAgXAAAAJGU1YmVlMjZmLWI4N2UtNGVlNi1iYzlhLWUyMjQ0YTA0YzI3ZQ.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Andrea Schostack','./Mulheres Palestrantes_files/qvDU2DKf.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Andréa Zambrana','./Mulheres Palestrantes_files/400922','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Andressa Chiara','./Mulheres Palestrantes_files/ca79853a5595723513d7da6caf13c94e.jpeg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Andressa Sivolella','./Mulheres Palestrantes_files/272868','Rio de Janeiro/RJ e');
INSERT INTO PALESTRANTES VALUES('Andreza Leite','./Mulheres Palestrantes_files/19ffbedf91fda0d0bc3f72d719902d66.jpeg',' São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Anielle Guedes','./Mulheres Palestrantes_files/placeholder-female.jpg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Anna Cruz','./Mulheres Palestrantes_files/0afb5c6c63c9e0ce7666528524ed6727.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Annelise Gripp','./Mulheres Palestrantes_files/6d3f646a5629bc5e23a73cec15cb4975.jpeg','Rio de Janeiro/RJ e São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Anyssa Ferreira','./Mulheres Palestrantes_files/anyssaferreira-296x300.jpg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Ariadne Pinheiro','./Mulheres Palestrantes_files/1ccd5f673dc4ab769c25180b5b4da5e1.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Ariane Parra','./Mulheres Palestrantes_files/416a736d3a63450abc19b91bbb7ce64b','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Ariane Feijó','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAm0AAAAJDVlYjAxMDI5LWNjMTgtNGQxMy1hNjZkLWEyMTY0YWIyNDVkZA.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Ariane Izac','./Mulheres Palestrantes_files/14958fc6544edc07d96d33d6b6ba6a0b.jpeg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Ariela Ranielly de Paula Silveira','./Mulheres Palestrantes_files/33342fd.jpg','Campinas/SP');
INSERT INTO PALESTRANTES VALUES('Augusta Guta Orofino','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Bárbara Barbosa','./Mulheres Palestrantes_files/763533','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Bárbara Cabral','./Mulheres Palestrantes_files/b0bf5ac8e0adfef3bd50004203ef9df7.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Bárbara Dariano Silva Suzuki','./Mulheres Palestrantes_files/e0914b23096ad6b2c4f16ae206f20b90.jpeg','Florianópolis/SC');
INSERT INTO PALESTRANTES VALUES('Barbara Jacinto','./Mulheres Palestrantes_files/photo.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Bianca Brancaleone','./Mulheres Palestrantes_files/HZdoLbi9.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Bianca Rosa','./Mulheres Palestrantes_files/63ddf8a769ed56c72f36a35c85b5d337.jpeg','Sorocaba/SP');
INSERT INTO PALESTRANTES VALUES('Bianca Marques','./Mulheres Palestrantes_files/17528956','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Cah Felix','./Mulheres Palestrantes_files/5debfa9b1fb78885f4e8df4915cb425f.jpeg','Salvador/BA');
INSERT INTO PALESTRANTES VALUES('Camila Achutti','./Mulheres Palestrantes_files/2078347','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Camila Campos','./Mulheres Palestrantes_files/2309096','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Camila Ferreira','./Mulheres Palestrantes_files/691624a81373dd9da912e1bda573fe10.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Camila Godoy','./Mulheres Palestrantes_files/placeholder-female.jpg','Florianópolis/SC');
INSERT INTO PALESTRANTES VALUES('Camila Haddad','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Camila Petry Feiler','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Carine Roos','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAgtAAAAJGUyZWNhODE0LTIzMTQtNDhmOC05ZWQ5LWE0ZjZhOWViNzEwMg.jpg','Curitiba/PR');
INSERT INTO PALESTRANTES VALUES('Carla de Bona','./Mulheres Palestrantes_files/AAEAAQAAAAAAAA26AAAAJGRmMjg4ZDA5LWEzYmYtNGZkOS1iZDM0LWI1ODVmNDMwYTgwZA.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Carla Moranga','./Mulheres Palestrantes_files/AAEAAQAAAAAAAArhAAAAJDI2MmY3NDU0LTQxZTItNDAyZC05MzQwLTFjMWE5NmRiMzU1Ng.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Camila Waz','./Mulheres Palestrantes_files/AAEAAQAAAAAAAArfAAAAJGQyNzA4NDQ1LTI2YjEtNGQ0NS1hOGU3LWY5MzU3Zjk0OWViOA.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Camilla Falconi Crispim','./Mulheres Palestrantes_files/5ed936f516df3562fe20b3a1338e7fb5.jpeg','João Pessoa/PB');
INSERT INTO PALESTRANTES VALUES('Carol Aguiar','./Mulheres Palestrantes_files/placeholder-female.jpg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Carol Patrocínio','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAedAAAAJDhjYzVjYTIxLTU1ZTMtNDQzNy05YmVhLTUwYTcwZDdmNjNhMw.jpg','Curitiba/PR');
INSERT INTO PALESTRANTES VALUES('Carolina Ruhman Sandler','./Mulheres Palestrantes_files/mini-carolina.png','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Caroline Burle','./Mulheres Palestrantes_files/6430260','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Celine Ramos','./Mulheres Palestrantes_files/i114D6dv_400x400.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Chaiane Simmler','./Mulheres Palestrantes_files/2c5fdc63b557f2588138056240fba94e','Salvador/BA');
INSERT INTO PALESTRANTES VALUES('Cíntia Mara','./Mulheres Palestrantes_files/f4d05fff206f059c2c5925df8dbf1bdb.jpeg','Itajaí/SC');
INSERT INTO PALESTRANTES VALUES('Clara Verena Battesini','./Mulheres Palestrantes_files/8d7d0c819f2b46610e81cecf0a122c8f','Belo Horizonte/MG');
INSERT INTO PALESTRANTES VALUES('Clarissa Barreto','./Mulheres Palestrantes_files/24b4c5a.jpg','Salvador/BA');
INSERT INTO PALESTRANTES VALUES('Clarissa Sóter','./Mulheres Palestrantes_files/9be3ac92a937615d8547ceec4072f177','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Claudia Carolina Boletti','./Mulheres Palestrantes_files/96289319fa2117a461d6cfbfbf3910cf.jpeg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Claudia Peruzzato','./Mulheres Palestrantes_files/AAEAAQAAAAAAAASIAAAAJDM2NDA0NjU0LTljMWEtNGQ1OS1hMGMyLWRkYjYyYzJhMTNkMg.jpg','São Bernardo/SP');
INSERT INTO PALESTRANTES VALUES('Conceição Morais','./Mulheres Palestrantes_files/7e8715a92e543bffbd9c1d41872ab06b','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Cynthia Torchi','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAWbAAAAJDkxM2EyMmU2LTNmYzctNDQ4MC05MWI5LWIzZmE3ZDBhZTk0Yg.jpg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Cynthia Tscha','./Mulheres Palestrantes_files/placeholder-female.jpg','Taubaté/SP');
INSERT INTO PALESTRANTES VALUES('Cynthia Zanoni','./Mulheres Palestrantes_files/acf2c97fd68b165d50bdf8f446afc0e7.jpeg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Cristal Bittencourt','./Mulheres Palestrantes_files/0d6bb01b9265417c64fd97c6fb19bc7c.jpeg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Daiany Maia de Andrade','./Mulheres Palestrantes_files/AAIAAgDGAAAAAQAAAAAAAAwtAAAAJDY1OWQ1ZGIwLTEwNGMtNDllMS04ODhlLTA4YjQzMGQyYjY3NQ.jpg','Salvador/BA');
INSERT INTO PALESTRANTES VALUES('Dalianny Vieira','./Mulheres Palestrantes_files/13053265','Ribeirão Preto/SP');
INSERT INTO PALESTRANTES VALUES('Daniela Araújo','./Mulheres Palestrantes_files/d0527f5a78b2e1575ccd9da7522a41c1.jpeg','Salvador/BA');
INSERT INTO PALESTRANTES VALUES('Daniela Bertocchi','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAxYAAAAJGYwNjlmMDcyLTdkMGYtNDM1OC1hYWEyLTA1YzdmMmUzZjIxOQ.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Daniela Castilho Schwab','./Mulheres Palestrantes_files/cf45e10a82c4f4638863f6d856df9ca2.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Daniela Feitosa','./Mulheres Palestrantes_files/0bd72ea.jpg','Campinas/SP');
INSERT INTO PALESTRANTES VALUES('Daniela Palumbo','./Mulheres Palestrantes_files/23b588ae707121505f5bcdedb8095227.png','Salvador/BA');
INSERT INTO PALESTRANTES VALUES('Daniela Petruzalek','./Mulheres Palestrantes_files/4bb860bd1c186becbfb64a5a40d8ee19.jpeg','Campinas/SP');
INSERT INTO PALESTRANTES VALUES('Daniela Senador','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAZAAAAAJGJjOWQ1OGJjLWM1MjYtNDg2My05MjlmLWQ0ZmJlODliNzg2ZA.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Daniela Victorazzi','./Mulheres Palestrantes_files/AAEAAQAAAAAAAA2WAAAAJGViNDJjZjgyLWIwN2MtNGE1OC1iYzQxLTI5OTcwM2U3ZGEzNA.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Daniele Andrade','./Mulheres Palestrantes_files/16c4248354041b76f72da23d755d6b7b','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Daniele Zandoná','./Mulheres Palestrantes_files/placeholder-female.jpg','Fortaleza/CE');
INSERT INTO PALESTRANTES VALUES('Danielle Teixeira','./Mulheres Palestrantes_files/5931990','Campinas/SP');
INSERT INTO PALESTRANTES VALUES('Danielle Vieira','./Mulheres Palestrantes_files/AAMAAgDGAAwAAQAAAAAAAAsAAAAAJDM2ZjVjZGU0LTRkNjUtNDk2YS1hZWY3LTdiZjQ4ZGYyM2M3Yg.jpg','Lauro de Freitas/BA');
INSERT INTO PALESTRANTES VALUES('Dayany Espíndola','./Mulheres Palestrantes_files/02582cea45d1ed66154b355aa1dc696d.jpeg','Sorocaba/SP');
INSERT INTO PALESTRANTES VALUES('Deb Xavier','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAvoAAAAJGY2ZjM4NGQ1LWRjNTQtNDZiYy1hNWYyLTdhYTBjMDZmMzMwMg.jpg','Rio de Janeiro/RJ e São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Déia Zoboli','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Deise Lima','./Mulheres Palestrantes_files/placeholder-female.jpg','Joinville/SC');
INSERT INTO PALESTRANTES VALUES('Denise Pagnussat','./Mulheres Palestrantes_files/3b13bc0.jpg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Denise Teófilo','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAhBAAAAJDJjNzE0YjE0LThjMjktNDZmNC1hMmViLTA2NWNmNzdhNGUwMg.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Diana Arnos','./Mulheres Palestrantes_files/4ce43cd2535d0afe50065a743af646e9.jpeg','Sorocaba/SP');
INSERT INTO PALESTRANTES VALUES('Diane Lima','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAI8AAAAJDc2NTczNDQ4LWY3ZDctNGJhZC04NTkwLWQ4NTAyNWU3MDBiMw.jpg','Osasco/SP');
INSERT INTO PALESTRANTES VALUES('Elisa Carlos Pereira ','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Elis Forgerini','./Mulheres Palestrantes_files/AAEAAQAAAAAAAA03AAAAJDViNGYwODRlLWM3MWEtNDRiNi05Y2MxLTdmNDZmYjQ4Mzg3MQ.jpg','Jundiaí/SP');
INSERT INTO PALESTRANTES VALUES('Elizabeth Regina Tscha','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Eluana Sievert Cardoso','./Mulheres Palestrantes_files/AAIA_wDGAAAAAQAAAAAAAAvQAAAAJDQ3M2Q1NDI5LTM2N2UtNDJiMi04NzQ4LWUwZTU3OTM0NWQ1MA.jpg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Emanuelle Menali','./Mulheres Palestrantes_files/0c019979ee02a71763ea2e44dd91e0bb.jpeg','Curitiba/PR');
INSERT INTO PALESTRANTES VALUES('Emmanuelle Richard','./Mulheres Palestrantes_files/cd920d13e1da5783e99a4372bc0f9fd2','Santa Luzia/MG');
INSERT INTO PALESTRANTES VALUES('Erica Ariano','./Mulheres Palestrantes_files/AAMAAgDGAAwAAQAAAAAAAA8gAAAAJDIwNGYxNzVkLTMyOTctNGY5ZS1hNjgyLTM4YzI3MDVhYjllZA.jpg','Natal/RN');
INSERT INTO PALESTRANTES VALUES('Érica Calil Nogueira','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAVEAAAAJDNhZWIxNTYyLTgzMjYtNDc2ZS04MmE0LTA3NjVhYTE4MDc3NA.jpg','Santo André/SP');
INSERT INTO PALESTRANTES VALUES('Erica Marques','./Mulheres Palestrantes_files/0b61b5ff9300a85587390e168845cbd4.jpeg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Érica Viana','./Mulheres Palestrantes_files/82a915535fb89f078db00ec645e05cc9','Curitiba/PR');
INSERT INTO PALESTRANTES VALUES('Erika Laíse','./Mulheres Palestrantes_files/0aaf2fe.jpg','Belo Horizonte/MG');
INSERT INTO PALESTRANTES VALUES('Estela Rocha','./Mulheres Palestrantes_files/AAEAAQAAAAAAAApsAAAAJDEyY2RjNjMxLTFjMmMtNDMwYS1iMTU2LWEzNzQ3MzFmMGRlYw.jpg','Belo Horizonte/MG');
INSERT INTO PALESTRANTES VALUES('Etienne Du Jardin','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAt8AAAAJGQ5MWY2OTkxLTczMDUtNDUyMi04OGM3LTBlZGY1ZTFmOGU3Yw.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Fabiana Rocha Batista','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Fabiany Lima','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Fernanda Bernardo','./Mulheres Palestrantes_files/393a8afb36c128e762e5130549d22dbe.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Fernanda Campagnucci','./Mulheres Palestrantes_files/0f196a83d85a2c66c3eb8678b3d96e7a.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Fernanda Lobato','./Mulheres Palestrantes_files/29c9108ca9fd4485e8b00858892bd0a5.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Fernanda Mano','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Fernanda Nascimento','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAuTAAAAJDAxMWM0MjExLWZkNmEtNDZkOC05YzAwLWM0ZmY5ODhhMmQ1NQ.jpg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Fernanda Nogueira','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Fernanda Trindade Monteiro','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Flávia Dias Fortes','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAnfAAAAJGZlNjI4MTM2LWM1YjQtNGExNy04NGFjLTBlNzM5ZWU1ZDc1Mg.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Francieli Viane','./Mulheres Palestrantes_files/1158ea2d0be5632609d067d2ebebacb9.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Francine Micheli','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAoYAAAAJDdiMTQxNzA0LWFmOTgtNDEwOC05OTVhLThkMzNhMmNkZTVhMQ.jpg','Belo Horizonte/MG');
INSERT INTO PALESTRANTES VALUES('Gabriela Galves Nunes','./Mulheres Palestrantes_files/aa602dcc4ba2afe200d65b808f3d713f','Ribeirão Preto/SP');
INSERT INTO PALESTRANTES VALUES('Geisa Santos','./Mulheres Palestrantes_files/5049246','Curitiba/PR');
INSERT INTO PALESTRANTES VALUES('Germanda Uchoa','./Mulheres Palestrantes_files/placeholder-female.jpg','Salvador/BA');
INSERT INTO PALESTRANTES VALUES('Giana de Almeida Pereira','./Mulheres Palestrantes_files/14f078115953cf2ea31d9891ac083eeb.jpeg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Gica Trierweiler Yabu','./Mulheres Palestrantes_files/568119.53d90b133af39.jpg','Florianópolis/SC');
INSERT INTO PALESTRANTES VALUES('Gina Gotthilf','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Giovana Penatti','./Mulheres Palestrantes_files/AAMAAgDGAAwAAQAAAAAAAA0uAAAAJGNiMTU2YWVmLWVhZDEtNGJiMC04MDM2LTdkOWI4OGU5ZWEwNA.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Gisele Késsia Gusmão Bizerril Gelschleiter','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Gisleine Silveira','./Mulheres Palestrantes_files/41052_1241696062527_7336928_n.jpg','Aracaju/SE');
INSERT INTO PALESTRANTES VALUES('Grazielle Mendes Rangel','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAXIAAAAJDVkZDE0YTVkLTkxNmYtNDRjZC04OTljLTNhOWQ5OThjYjNmMA.jpg','Montreal/Canadá');
INSERT INTO PALESTRANTES VALUES('Halina Medina','./Mulheres Palestrantes_files/AAMAAQDGAAwAAQAAAAAAAAvyAAAAJGU2Zjg1NzU1LTY4MjMtNDI4NS04MTlhLTJhOTJmNzc0MmJmZg.jpg','Belo Horizonte/MG');
INSERT INTO PALESTRANTES VALUES('Hanna Pereira','./Mulheres Palestrantes_files/92f91622d6f40aee53dae82376a1b725','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Haydée Svab','./Mulheres Palestrantes_files/96b81d9c691891f599a9c35dcbb412f0.png','São Vicente/SP');
INSERT INTO PALESTRANTES VALUES('Helena Margarido','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Hendy Almeida','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Hevlin Costa','./Mulheres Palestrantes_files/a3a83c902112cedccc0e071147027a72.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Iaci Gomes','./Mulheres Palestrantes_files/AAMAAQDGAAwAAQAAAAAAAA6mAAAAJDY5ZmJlZWVhLTRmMWUtNGFjNS1iMTljLWMxYTE4OGYzM2ZmNQ.jpg','Jundiaí/SP');
INSERT INTO PALESTRANTES VALUES('Isabella Silveira','./Mulheres Palestrantes_files/4542747','Belém/PA');
INSERT INTO PALESTRANTES VALUES('Ingrid Mantonavi','./Mulheres Palestrantes_files/018be55.jpg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Ivanise Gomes','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAg_AAAAJGYyMmM0NzM1LTEyZGYtNDFkMC04MmMwLTI5NTE5ZmM5OWQxMw.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Izadora Ribeiro Perkoski','./Mulheres Palestrantes_files/b58009e9c7a0dee56bfb552e58f69ca8.jpeg','Campinas/SP');
INSERT INTO PALESTRANTES VALUES('Izza Simões','./Mulheres Palestrantes_files/AAMAAgDGAAwAAQAAAAAAAA5AAAAAJDRkZWIyZTA3LTg3ZTctNGNiZi04ODhlLTY2NGZiYTdjYjNhMQ.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Jacqueline Yumi Asano','./Mulheres Palestrantes_files/24320336','João Pessoa/PB');
INSERT INTO PALESTRANTES VALUES('Janine Saponara','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAvoAAAAJDgxMDczMjgwLWUwOTYtNDI1MS1hYzRlLThlYjU1ZTM5NTMzMg.jpg','Florianópolis/SC');
INSERT INTO PALESTRANTES VALUES('Janynne Gomes','./Mulheres Palestrantes_files/AAMABADGAAwAAQAAAAAAAAoJAAAAJDEzNTE5YjY4LTBhMzEtNDcyNC04YWIwLTgxNTU2NDdkYWQ0Yg.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Jeliel Mendes','./Mulheres Palestrantes_files/4261484','Governador Valadares/MG');
INSERT INTO PALESTRANTES VALUES('Jennifer Payne','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Jessica Temporal','./Mulheres Palestrantes_files/35beca46843e4adcbd43df1bc93ce38b.jpeg','Blumenau/SC');
INSERT INTO PALESTRANTES VALUES('Jessilanny Nóbrega','./Mulheres Palestrantes_files/placeholder-female.jpg','Osasco/SP');
INSERT INTO PALESTRANTES VALUES('Josilene Santana','./Mulheres Palestrantes_files/placeholder-female.jpg','Campina Grande/PB');
INSERT INTO PALESTRANTES VALUES('Joviane Jardim','./Mulheres Palestrantes_files/2b1269b.jpg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Juciellen Cabrera','./Mulheres Palestrantes_files/0b8df4309d2e40efce1208242c35a058','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Juily Manghirmalani','./Mulheres Palestrantes_files/AAIAAgDGAAAAAQAAAAAAAA1PAAAAJGI3YTM0ZGI2LTI4ODItNGY1OS04Y2VkLWZkYWJiOTBiZmVmOA.jpg','Guarulhos/SP');
INSERT INTO PALESTRANTES VALUES('Júlia Albuquerque','./Mulheres Palestrantes_files/fb39d8165fcc2edf3375d0eba8b0d6ff.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Julia Stateri','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAjwAAAAJDkzYmFkMTU3LTYwNjUtNDFlOC04NWVhLTRiMDZjZTU0ZTlkZg.jpg','Maceió/AL');
INSERT INTO PALESTRANTES VALUES('Juliana de Bittencourt Escobar','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAjqAAAAJGNkYjM1YTgzLTYxMzItNDkyMC1iNGUxLWJjMjBiYzg0YmNlMA.jpg','Campinas/SP');
INSERT INTO PALESTRANTES VALUES('Juliana Carvalho','./Mulheres Palestrantes_files/AAMABADGAAwAAQAAAAAAAA6zAAAAJGRjMGVhYmE3LTQ5ZTgtNGU3Yy04NTJkLTQ5NTU2NjJlNDllOA.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Juliana Chahoud','./Mulheres Palestrantes_files/placeholder-female.jpg','João Pessoa/PB');
INSERT INTO PALESTRANTES VALUES('Juliana Félix Nunes','./Mulheres Palestrantes_files/3291727','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Juliana Fernandes','./Mulheres Palestrantes_files/037d35f865f95571c3194b4c84a4915b.jpeg','Goiânia/GO');
INSERT INTO PALESTRANTES VALUES('Juliana Fernandes','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Juliana Guerra','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAviAAAAJGFhMzc0MDFiLWZjNTAtNDE1YS1hZGE2LWYxMjU3MTRkZWJmMg.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Juliana Hercowitz','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAd8AAAAJDc0MTdjYWJjLWQxYTMtNGQ1NS1hNDQxLWIwZjAxNmZmZjhmMA.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Juliana Wallauer','./Mulheres Palestrantes_files/AAIA_wDGAAAAAQAAAAAAAAxxAAAAJDc0NTMyMGNmLWI3MGUtNGRlOC05ZGEwLWI1MGYzMjkzODkwOQ.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Juliene Alves','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAl0AAAAJDM1OWFmZTI2LTM0OTQtNDMwMy1hN2Q2LTUyODgzNjg5YTNhZg.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Julyane Miranda','./Mulheres Palestrantes_files/APVpL4L6_400x400.jpg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Karen Figueiredo','./Mulheres Palestrantes_files/ad74bd0e6c00310471c4761e1ec73f5d','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Karina Girardi Roggia','./Mulheres Palestrantes_files/5774b104265c725d9ea7e65b5411a2c2.jpeg','Cuiabá/MT');
INSERT INTO PALESTRANTES VALUES('Karina Martins','./Mulheres Palestrantes_files/placeholder-female.jpg','Joinville/SC');
INSERT INTO PALESTRANTES VALUES('Karla Patriota Bronsztein','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Kathlen Amado','./Mulheres Palestrantes_files/3bae151.jpg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Kelly Kiyumi','./Mulheres Palestrantes_files/82810bb4e5c8a9caecda9f48ed285ffc.jpeg','Brasília/DF');
INSERT INTO PALESTRANTES VALUES('Krystal Campioni','./Mulheres Palestrantes_files/891f39aa823d65aed365e0b801a58af8.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Laís Carvalho','./Mulheres Palestrantes_files/2b1fd1c.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Lais de Lima','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAROAAAAJDdiM2Q2ZGMyLWY5NGUtNDUxOC1iZmRmLWE0MGEyNDdhOTE4Mg.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Larissa Sá ','./Mulheres Palestrantes_files/55ea4b542e9aef1c4cfc45e30100b9a9','Belém/PA');
INSERT INTO PALESTRANTES VALUES('Laura Gurgel','./Mulheres Palestrantes_files/placeholder-female.jpg','Brasilia/DF');
INSERT INTO PALESTRANTES VALUES('Laura Nobrega','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAeOAAAAJDY0Yzc1ZDk4LTExYTItNGJkZS1hNWViLTAxZWQyYTllNjQwMw.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Letícia Passarelli Canova','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Leticia Figueira','./Mulheres Palestrantes_files/a47dc8cc9354985bd4f688c78e910261.png','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Letícia Millião','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAmJAAAAJDJkMDQ1YzQ0LThhZGEtNGZiNS1hMjdkLTIwNmJjMDFhZTc2MA.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Letícia Motta','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAlHAAAAJDAyMDMwNjkwLWMxNTYtNDIyYy1iYzYxLWRjOGM0MmQzMjI3NA.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Leticia Portella','./Mulheres Palestrantes_files/96f6148ae5af63f90246a3817686b457.jpeg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Leticia Pozza','./Mulheres Palestrantes_files/0ce2411.jpg','Ribeirão Preto/SP');
INSERT INTO PALESTRANTES VALUES('Letticia Nicoli','./Mulheres Palestrantes_files/13442773','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Lhaís Rodrigues','./Mulheres Palestrantes_files/171d49d996b7c9c2d93af7066948dc47.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Lidiane De Souza Monteiro','./Mulheres Palestrantes_files/b71e8a1577930c3d84478e5c325d5d53.jpeg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Lígia Bernar','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAwCAAAAJDljZGVjYTY5LWY3NWYtNDM5Yi1hYmExLTAyNDUwNmJlY2JjZg.jpg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Lígia Zeppelini','./Mulheres Palestrantes_files/7f92138973430327cc2a6c2758c31b15.png','Belém/PA');
INSERT INTO PALESTRANTES VALUES('Liliam Leal','./Mulheres Palestrantes_files/da72818e353c00159b1e259359de6fe0','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Lilian Gonçalves','./Mulheres Palestrantes_files/16c4a29.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Lina Garrido','./Mulheres Palestrantes_files/08a9d15.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Lisi Moraes','./Mulheres Palestrantes_files/23afdd1.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Loiane Groner','./Mulheres Palestrantes_files/59545','Florianópolis/SC');
INSERT INTO PALESTRANTES VALUES('Luana Weitzel','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Luciana Guerra','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAs9AAAAJDEzMjhhMmY3LTBhZTMtNDYyMS1hNTI1LWNkNjZiMmViOWVhZA.jpg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Luciana Minev','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Luciana Stabile','./Mulheres Palestrantes_files/placeholder-female.jpg','Manaus/AM');
INSERT INTO PALESTRANTES VALUES('Luiza Guerra','./Mulheres Palestrantes_files/65c5b3ac0eeae6d90fea315e72068f16.jpeg','Ribeirão Preto/SP');
INSERT INTO PALESTRANTES VALUES('Macarena Garcia','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAliAAAAJDZmZWIxM2RhLTJiM2MtNDIyZS04OTViLTc0NzI4YjA2OGY1Nw.jpg','Belo Horizonte/MG');
INSERT INTO PALESTRANTES VALUES('Maitê Balhester','./Mulheres Palestrantes_files/7ee96fafef481d455a222c6102cf3528.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Marcela Costa','./Mulheres Palestrantes_files/placeholder-female.jpg','Santo André/SP');
INSERT INTO PALESTRANTES VALUES('Marcela Milano','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAxHAAAAJGIwYjc2Mzc5LWM3MDAtNGM1NC04MTQyLTk4MDc2ZGNiMDE2ZQ.jpg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Marcela Oliveira','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAMzAAAAJGYwZjJjYmM1LTEzODktNDFmZS05YzFkLWE3ODUwN2FlNDcwYQ.jpg','Curitiba/PR');
INSERT INTO PALESTRANTES VALUES('Marcela Santos','./Mulheres Palestrantes_files/ac3d63657b5e83530e24cde0172776c0.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Márcia Santos Almeida','./Mulheres Palestrantes_files/67f4a42acf26552b0212c6fb6e4b186f.jpeg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Maria Clara Santana','./Mulheres Palestrantes_files/78b75aad21ed5ed351d9822d77acd7fc.jpeg','Goiânia/GO');
INSERT INTO PALESTRANTES VALUES('Marina Miranda','./Mulheres Palestrantes_files/placeholder-female.jpg','Maceió/AL');
INSERT INTO PALESTRANTES VALUES('Mariana Araujo Mioto','./Mulheres Palestrantes_files/acf4d17d0e0a7f8f0ba61f4d7895c489.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Mariana Camargo','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Mariana Gomes ','./Mulheres Palestrantes_files/2fec6491815582734b1ddc97449a44a4','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Mariana Janeiro','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAkQAAAAJGZlMjFlZDM5LWJmY2ItNDYwMi04MzRmLTlkZWMwOTlmNjNkNw.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Mariana Maneira','./Mulheres Palestrantes_files/852d4d7999da6483617ca28da2383b4d.jpeg','Jundiaí/SP');
INSERT INTO PALESTRANTES VALUES('Mariana Matos','./Mulheres Palestrantes_files/1b21abc.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Marianne Costa','./Mulheres Palestrantes_files/c2eae133a7e4c21231cb8e886497198c','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Mariela Castro','./Mulheres Palestrantes_files/4c2f1d898d747dab7585d050ac8273ca','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Marina Arilha Silva','./Mulheres Palestrantes_files/022ff18e9fba3f2db09f7e35f1c5c339','Curitiba/PR');
INSERT INTO PALESTRANTES VALUES('Maristela Moura','./Mulheres Palestrantes_files/1f18906.jpg','Jundiaí/SP');
INSERT INTO PALESTRANTES VALUES('Marta Preuss','./Mulheres Palestrantes_files/901ef2fc184b347a5f5717c2ddc3f5e6.jpeg','Indaiatuba/SP');
INSERT INTO PALESTRANTES VALUES('Marla Dore','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAMtAAAAJDMyZDY1Y2UyLTAxZWUtNDk2Ny1iODI1LWJjMmY4ODQ0NzFhZQ.jpg','Florianópolis/SC');
INSERT INTO PALESTRANTES VALUES('Martina Scherrer','./Mulheres Palestrantes_files/e3a29c667bd11908fe3006b90bc61619.jpeg','Salvador/BA');
INSERT INTO PALESTRANTES VALUES('Mayara Carolina de Paula','./Mulheres Palestrantes_files/4465d8b13bc5825ffbe1ebea01cc7cc8','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Mayara Miranda','./Mulheres Palestrantes_files/10636124_932122716807075_2937596775672211091_n.jpg','Fortaleza/CE');
INSERT INTO PALESTRANTES VALUES('Mayra Fonseca','./Mulheres Palestrantes_files/AAEAAQAAAAAAAA3HAAAAJDI0NGJiMTRkLTJjMmUtNDJkNy04YTdkLWRkNGUwNzZmMTc2ZA.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Mayra R Souza','./Mulheres Palestrantes_files/13318439','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Maysa de Oliveira','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAwGAAAAJGQxMGE3ZWNkLTgxNzUtNDA3My04ZDBkLWVjN2E2ZDE4OGUyNg.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Meli Malatesta','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAlvAAAAJDUyODNlMzE2LWRiNmMtNDUxYy1hNDA3LTZhMWNmMWUxN2U0MA.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Melissa Devens','./Mulheres Palestrantes_files/ad3b9541600ce3b1e57fdebfa6191c20.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Michele Costa','./Mulheres Palestrantes_files/placeholder-female.jpg','Campinas /SP');
INSERT INTO PALESTRANTES VALUES('Michelle Guimarães','./Mulheres Palestrantes_files/placeholder-female.jpg','Rolim de Moura/RO');
INSERT INTO PALESTRANTES VALUES('Mila Paes Leme Marques','./Mulheres Palestrantes_files/placeholder-female.jpg','Manaus/AM');
INSERT INTO PALESTRANTES VALUES('Mimi Newton','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAxVAAAAJDQyOTdjYzZiLTBlNmQtNDgwYS1iMmNmLTk3ZTc2YjM4MGY5MA.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Mirian Meliani Nunes','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Mônica Bulgari','./Mulheres Palestrantes_files/d0cee09c38060345dcdc63d055f0bc54.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Mychelle Jacob','./Mulheres Palestrantes_files/d4be3cb0a04673af6d875058c2c2effe','Campinas/SP');
INSERT INTO PALESTRANTES VALUES('Myrian Connor','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAjGAAAAJDg2ZGU5MWIzLThkYWItNDkxMS1iYTk0LTdmZTA1OGFhMDIxMg.jpg','Olinda/PE ');
INSERT INTO PALESTRANTES VALUES('Nadezhda Bezerra Batista','./Mulheres Palestrantes_files/placeholder-female.jpg','Castanhal/PA');
INSERT INTO PALESTRANTES VALUES('Nádia Rebouças','./Mulheres Palestrantes_files/AAIAAgDGAAAAAQAAAAAAAAmeAAAAJDBmZTY5NGExLTQxOTMtNDc2Yi1hOTkxLTY4OWI1MjUzYTkxZg.jpg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Natália Menhem','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAuTAAAAJDU1YmY3YTU1LTdmMmEtNDhmOS05OTFhLTk3M2E0NjczYjVmYQ.jpg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Natascha Hun','./Mulheres Palestrantes_files/60a21ab75db2e268aa55b2973e2f69c8','Belo Horizonte/MG');
INSERT INTO PALESTRANTES VALUES('Natasha Romariz','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAh8AAAAJGYxZDdmZTZhLTFhZGQtNDZhNy04MDY2LTgwZTRmNjcyZjQ1ZA.jpg','Sorocaba/SP');
INSERT INTO PALESTRANTES VALUES('Nathalia Novaes Leonessa','./Mulheres Palestrantes_files/aee3962dd39be56420d63161bb0c859c','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Nathalia Sautchuk Patrício','./Mulheres Palestrantes_files/ce31b72323ed84b80253f4340c98c9dd.png','Sorocaba/SP');
INSERT INTO PALESTRANTES VALUES('Nessa Rodrigues','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAqnAAAAJDllZGQzNWVhLWUyMTQtNDJlNS05NGMxLTNlMjlkNWM1OWQ2Yw.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Olivia Janequine','./Mulheres Palestrantes_files/371e87d45d7e34a1ed6f82a665714106.jpeg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Paola Tucunduva','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Patricia Almeida Ferreira','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Patricia Arruda','./Mulheres Palestrantes_files/b909b45ac714b7e019b3e6c3c1623916','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Patricia de Paula','./Mulheres Palestrantes_files/a125fea1abff71dd443b09ba3918c482','União da Vitória/PR');
INSERT INTO PALESTRANTES VALUES('Patricia Kouzmine','./Mulheres Palestrantes_files/AAIA_wDGAAAAAQAAAAAAAAy7AAAAJGUwNTQxMGJkLTJmMmYtNDliMy05NGFmLTM5MjA3NTFmY2I3OQ.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Patricia Ramos de Quadros','./Mulheres Palestrantes_files/placeholder-female.jpg','Brasília/DF');
INSERT INTO PALESTRANTES VALUES('Patrícia Ribeiro','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Patrícia SantAnna','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAdHAAAAJDE5NDQxMTQ0LWU0M2YtNDQzOC1iZTQ4LWY1N2UwZTE0ODhkYw.jpg','Campinas/SP');
INSERT INTO PALESTRANTES VALUES('Paula Diniz','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Paula Faria','./Mulheres Palestrantes_files/ed70023e19882637aef103170e81f365.jpeg','Belo Horizonte/MG');
INSERT INTO PALESTRANTES VALUES('Paula Grangeiro','./Mulheres Palestrantes_files/2524981','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Paula Quintão','./Mulheres Palestrantes_files/placeholder-female.jpg','Manaus/AM');
INSERT INTO PALESTRANTES VALUES('Paulinha Paz','./Mulheres Palestrantes_files/08df93d.jpg','Salvador/BA');
INSERT INTO PALESTRANTES VALUES('Preta Emmeline','./Mulheres Palestrantes_files/placeholder-female.jpg','Natal/RN');
INSERT INTO PALESTRANTES VALUES('Priscila Chagas','./Mulheres Palestrantes_files/0ecd5129c8defe57116e45a8078c2a68.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Rafaela Marques','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAimAAAAJDNmY2FjMWI5LWViODktNDhhZi04N2Y3LTA2MjQxNDUzMDM5YQ.jpg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Rafaella Cavalca','./Mulheres Palestrantes_files/placeholder-female.jpg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Raissa dos Santos Ferreira','./Mulheres Palestrantes_files/68328f099165564e758f8bd7c0a7ae05.jpeg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Raissa Klain Belchior','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAh_AAAAJDg3YTdhY2RhLWFlMTItNGJhYS04MmZjLWIzNzA0ZDZkODRmYw.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Raquel Camargo','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAlqAAAAJGZmYzk4Y2JmLTU4OWEtNDhmMS04MmU3LTdjNjFmMzM5MjZjYg.jpg','Belo Horizonte/MG');
INSERT INTO PALESTRANTES VALUES('Raquel de Oliveira Santos Lira','./Mulheres Palestrantes_files/21d98c7ad075efd639ffbf0e50f9af35','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Raquel Prado','./Mulheres Palestrantes_files/cf9ab0b3894b990e19f4e85d6b62f34b.png','Curitiba/PR');
INSERT INTO PALESTRANTES VALUES('Raquel Preto','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Raquel Santachiara','./Mulheres Palestrantes_files/placeholder-female.jpg','Vila Velha/ES');
INSERT INTO PALESTRANTES VALUES('Rayanny Nunes','./Mulheres Palestrantes_files/placeholder-female.jpg','Natal/RN');
INSERT INTO PALESTRANTES VALUES('Reimy Solange Chagas','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Renata Machado Tárrio','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAMUAAAAJDUxZWE0OGQ2LTk0N2MtNDIwOS04MzBlLWNjM2RkNzIzOGJlMA.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Renata Masseroni','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Rebeca Bordini','./Mulheres Palestrantes_files/cb653395be591fe2387eddfb9319e4a3.jpeg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Rebeca Serpa','./Mulheres Palestrantes_files/acac3abd195659bf7d40086bae543427.jpeg','Osasco/SP');
INSERT INTO PALESTRANTES VALUES('Rita Lino','./Mulheres Palestrantes_files/placeholder-female.jpg','Santos/SP');
INSERT INTO PALESTRANTES VALUES('Robertta Mota','./Mulheres Palestrantes_files/placeholder-female.jpg','Fortaleza/CE');
INSERT INTO PALESTRANTES VALUES('Ronaiza Cardoso','./Mulheres Palestrantes_files/f45e8318bf829e33e34c1b8b10e2cb1d.jpeg','Brasilia/DF');
INSERT INTO PALESTRANTES VALUES('Rosália Cipriano Oliveira','./Mulheres Palestrantes_files/AAMAAgDGAAwAAQAAAAAAAA8YAAAAJDg3YmI2ODkwLThlNjAtNGEyYy04MDUxLWJiODM1NTRkZTY3YQ.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Rosi Rodrigues','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Rosicléia Frasson','./Mulheres Palestrantes_files/6be2f94c93c57c403c131e6c80b6c356.jpeg','Joinville/SC');
INSERT INTO PALESTRANTES VALUES('Rute Faria','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAlyAAAAJDkzYzQ4MmMzLWNiYWItNDUzNC05YjA5LTU3ZGQ3OTRkMzYxMA.jpg','Belo Horizonte/MG');
INSERT INTO PALESTRANTES VALUES('Samanta Cicilia','./Mulheres Palestrantes_files/d0e2beb1970140f2b36a8aa334c068a8.jpeg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Samantha Rosa','./Mulheres Palestrantes_files/2932644','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Samira Almeida','https://storymax.me/images/samira_lowres.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Sandy Maciel','./Mulheres Palestrantes_files/6650913','Fortaleza/CE');
INSERT INTO PALESTRANTES VALUES('Silvana Bahia','./Mulheres Palestrantes_files/destaque_1502386742SilvanaBahia.jpg','Rio de Janeiro/RJ');
INSERT INTO PALESTRANTES VALUES('Silvia Helena Rocha Campos','./Mulheres Palestrantes_files/92cb9418155e8ae0de2214fafc908a43.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Silvia Valadares','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Simone Amorim','./Mulheres Palestrantes_files/0d3d7d27f9da8e0f1d2b69c626c9b4cc.jpeg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Simone Pittner','./Mulheres Palestrantes_files/9ac1f87ee020a87404cc22a3185966b1.jpeg','Florianópolis/SC e São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Soraia Lima','./Mulheres Palestrantes_files/6z7rU3yQ_400x400.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Stella Dauer','./Mulheres Palestrantes_files/07bab57.jpg','São Bernardo do Campo/SP');
INSERT INTO PALESTRANTES VALUES('Suzana Bueno','./Mulheres Palestrantes_files/AAEAAQAAAAAAAA29AAAAJDBiMjY0ZjkxLTBhMDUtNDg3NC04ZmNlLTU4MmQyNjRjZGJlYQ.jpg','Campinas/SP');
INSERT INTO PALESTRANTES VALUES('Suzana Cohen','./Mulheres Palestrantes_files/placeholder-female.jpg','Belo Horizonte/MG');
INSERT INTO PALESTRANTES VALUES('Tais Oliveira','./Mulheres Palestrantes_files/placeholder-female.jpg','Guarulhos/SP');
INSERT INTO PALESTRANTES VALUES('Talita Lombardi','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Talita Pagani','./Mulheres Palestrantes_files/7b6f40fb2885d5c45f5f676df4bab5fb.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Talita Rossari ','./Mulheres Palestrantes_files/dd46d758ae021e8f78c9cd8cefef0c27.jpeg','Florianópolis/SC');
INSERT INTO PALESTRANTES VALUES('Tancicleide Gomes','./Mulheres Palestrantes_files/2ce3c115479dbae97ee681b28ffc6725.jpeg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Tatiana Assali','./Mulheres Palestrantes_files/3ed51c2d50a2549abbfd64875b4ff641','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Tatiana Lourenço','./Mulheres Palestrantes_files/c5bccef3550aecfec2f68c38626c0860','Fortaleza/CE');
INSERT INTO PALESTRANTES VALUES('Tatiana Pezoa','./Mulheres Palestrantes_files/placeholder-female.jpg','Campinas/SP');
INSERT INTO PALESTRANTES VALUES('Tatiana Tosi','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Tatiana Vargas Maia','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Tatiane Conceição Vergueiro','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Tatti Maeda','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAxBAAAAJDU3ODJiZjg5LTk1N2EtNGRmOS04YzNiLTg0ZGVjNWU1Njg3ZA.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Tayra Vasconcelos','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Thais Gentile','./Mulheres Palestrantes_files/placeholder-female.jpg','Belém/PA');
INSERT INTO PALESTRANTES VALUES('Thais Godinho','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Thais Moura de Freitas','./Mulheres Palestrantes_files/placeholder-female.jpg','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Thais Souza','./Mulheres Palestrantes_files/placeholder-female.jpg','Salvador/BA');
INSERT INTO PALESTRANTES VALUES('Thaisa Mirely','./Mulheres Palestrantes_files/54cf6dffa00e7d9f58f44da987cf53e6','Recife/PE');
INSERT INTO PALESTRANTES VALUES('Thaise Saeter','./Mulheres Palestrantes_files/aef601b2a2eb44af917418e2ae9fa339','Porto Alegre/RS');
INSERT INTO PALESTRANTES VALUES('Thalita Nick Pinheiro','./Mulheres Palestrantes_files/e4103d70005e648a639d33a287a8dc0d.jpeg','Belo Horizonte/MG');
INSERT INTO PALESTRANTES VALUES('Thaty Moura','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Uafa Smaili','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Valéria Barros','./Mulheres Palestrantes_files/4bbf316b66f8a754e0f9cdf67254515d.jpeg','Goiânia/GO');
INSERT INTO PALESTRANTES VALUES('Vanessa Gonçalves Ferreira','./Mulheres Palestrantes_files/1ddbed5.jpg','Belo Horizonte/MG');
INSERT INTO PALESTRANTES VALUES('Vanessa Kukul','./Mulheres Palestrantes_files/1b874de.jpg','Caxias do Sul/RS');
INSERT INTO PALESTRANTES VALUES('Vanessa Me Tonini','./Mulheres Palestrantes_files/2401246468e994e03713d5b83c16adaa.jpeg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Vanessa Queiroz','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAuwAAAAJGFkZjQ4ODBhLWMwY2UtNDg1MC04MTI5LTk2NzI1ODkwYzkyYQ.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Vanessa Rocha','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Vera Cristina de Moraes','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAGDAAAAJDhmOGRhMjExLWNkZGMtNDBhMy1hNmI4LWZjZjUwNTRlMWE4NQ.jpg','Londrina/PR');
INSERT INTO PALESTRANTES VALUES('Vivian Vianna','./Mulheres Palestrantes_files/AAEAAQAAAAAAAATqAAAAJGQ2ZDgyN2FkLThkYmItNDBiOC05YzI3LWU4Mzk0ZmQyNzZjZA.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Viviane Vilella','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO PALESTRANTES VALUES('Yanne Moreira','./Mulheres Palestrantes_files/e8922e930f20a9daa1e0a5169235ba4e.jpeg','Curitiba/PR');
INSERT INTO PALESTRANTES VALUES('Yasodara Córdova','./Mulheres Palestrantes_files/7e089e6db99186280cfe1bbd1a80117c.png','São Paulo/SP');

-- Verificando banco populado
select * from PALESTRANTES;


