CREATE TABLE mytable(
   FIELD1              INTEGER  NOT NULL PRIMARY KEY 
  ,Nome                VARCHAR(42) NOT NULL
  ,TEMAS_DE_INTERESSES VARCHAR(92) NOT NULL
);
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (0,'Adriana Antunes','Comunicação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (1,'Adriana da Rosa Amaral','produção audiovisual');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (2,'Alda Rocha','estudos de gênero');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (3,'Alessandra Guglieri','Comunicação e cibercultura');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (4,'Alice Coutinho','teorias da ficção-científica e imaginário tecnológico');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (5,'Aline de Campos','subculturas');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (6,'Aline M. C. Freitas','etnografia virtual');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (7,'Aline Pêgas','metodologias de pesquisa online');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (8,'Alline Jajah','padrões de consumo na web');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (9,'Alline Oliveira','cenas');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (10,'Alynne Cid','fandoms');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (11,'Amanda Santana','gêneros');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (12,'Amanda Silva Vieira','plataformas de música online');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (13,'Amanda Vilela','cultura pop');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (14,'Amanda Zacarias Marinho','UX Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (15,'Amélia Pessoa','Front-end');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (16,'Ana Antar','Rails');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (17,'Ana Barcellos','Web Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (18,'Ana Carolina Alves Rodrigues','Design thinking');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (19,'Ana Clarissa','Leadership');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (20,'Ana Del Mar','Creative process');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (21,'Ana Fontes','Empreendedorismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (22,'Ana Julia Ghirello','Gestão de Projetos');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (23,'Ana Luíza Avellar','Cocriação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (24,'Ana Luiza Bastos','Publicidade');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (25,'Ana Paula Coelho Barbosa','Desenvolvimento web');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (26,'Ana Paula da Silva Mendes','UX');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (27,'Ana Paula de Luca','Métodos Ágeis');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (28,'Ana Paula Gaspar','Data Science');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (29,'Ana Paula Gomes','Comunicação e Informação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (30,'Ana Paula Marques','Educação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (31,'Ana Paula Vargas Maia','Ensino e Pesquisa');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (32,'Ana Raquel Calháu Pereira','Social Media');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (33,'Ana Ribeiro','Marketing digital');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (34,'Ana Rute Mendes','Jornalismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (35,'Ana Schwendler','Planejamento');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (36,'Ananda Carvalho','Comportamento do consumidor');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (37,'Andrea Barberà','Conteúdo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (38,'Andrea Siqueira','Segurança da Informação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (39,'Andrea Schostack','Linux');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (40,'Andréa Zambrana','Shell Script');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (41,'Andressa Chiara','Comunicação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (42,'Andressa Sivolella','Networking');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (43,'Andreza Leite','Marketing');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (44,'Anielle Guedes','Inovação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (45,'Anna Cruz','Empreendedorismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (46,'Annelise Gripp','Mídias Sociais');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (47,'Anyssa Ferreira','Google');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (48,'Ariadne Pinheiro','Cloud');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (49,'Ariane Parra','Java');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (50,'Ariane Feijó','App Engine');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (51,'Ariane Izac','Lean');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (52,'Ariela Ranielly de Paula Silveira','Startups');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (53,'Augusta Guta Orofino','Machismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (54,'Bárbara Barbosa','Diversidade');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (55,'Bárbara Cabral','Social Media');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (56,'Bárbara Dariano Silva Suzuki','SAC 2.0');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (57,'Barbara Jacinto','Relacionamento');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (58,'Bianca Brancaleone','Desenvolvimento Front e Back-end');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (59,'Bianca Rosa','CakePHP3');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (60,'Bianca Marques','Programação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (61,'Cah Felix','Rails4');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (62,'Camila Achutti','Laravel5');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (63,'Camila Campos','UX Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (64,'Camila Ferreira','Front-end');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (65,'Camila Godoy','JavaScript');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (66,'Camila Haddad','Rails');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (67,'Camila Petry Feiler','Agile');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (68,'Carine Roos','Software Development');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (69,'Carla de Bona','Front-end');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (70,'Carla Moranga','UI Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (71,'Camila Waz','Web Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (72,'Camilla Falconi Crispim','Economia Colaborativa');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (73,'Carol Aguiar','UX');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (74,'Carol Patrocínio','HCI');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (75,'Carolina Ruhman Sandler','Desenho de Serviços');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (76,'Caroline Burle','Mulheres na Tecnologia');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (77,'Celine Ramos','Android');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (78,'Chaiane Simmler','Kotlin');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (79,'Cíntia Mara','Data Science');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (80,'Clara Verena Battesini','Big Data');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (81,'Clarissa Barreto','NoSQL');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (82,'Clarissa Sóter','Python');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (83,'Claudia Carolina Boletti','Mulheres na Tecnologia');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (84,'Claudia Peruzzato','Live Games');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (85,'Conceição Morais','Teatro');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (86,'Cynthia Torchi','Gestão de Projetos');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (87,'Cynthia Tscha','Game Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (88,'Cynthia Zanoni','Analista de TI');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (89,'Cristal Bittencourt','Educadora');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (90,'Daiany Maia de Andrade','Blogueira');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (91,'Dalianny Vieira','Evangelizadora Joomla');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (92,'Daniela Araújo','Desenvolvimento Back-end');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (93,'Daniela Bertocchi','Mulheres na Computação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (94,'Daniela Castilho Schwab','Agile');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (95,'Daniela Feitosa','Startups');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (96,'Daniela Palumbo','Gestão de Conteúdo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (97,'Daniela Petruzalek','Métricas');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (98,'Daniela Senador','Marketing Digital');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (99,'Daniela Victorazzi','Planejamento');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (100,'Daniele Andrade','Pesquisa');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (101,'Daniele Zandoná','Empreendedorismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (102,'Danielle Teixeira','Marketing Digital');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (103,'Danielle Vieira','Negócios');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (104,'Dayany Espíndola','Empreendedorismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (105,'Deb Xavier','Desenvolvimento de Produto');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (106,'Déia Zoboli','Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (107,'Deise Lima','Mentoria');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (108,'Denise Pagnussat','Monetização');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (109,'Denise Teófilo','Growth');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (110,'Diana Arnos','Análise de Negócios');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (111,'Diane Lima','Planejamento Estratégico');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (112,'Elisa Carlos Pereira','Gestão de Projetos');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (113,'Elis Forgerini','JavaScript');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (114,'Elizabeth Regina Tscha','Programação Funcional');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (115,'Eluana Sievert Cardoso','Desenvolvimento de Jogos');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (116,'Emanuelle Menali','Web');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (117,'Emmanuelle Richard','marketing e comunicação digital');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (118,'Erica Ariano','economia criativa');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (119,'Érica Calil Nogueira','economia colaborativa');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (120,'Erica Marques','hackschooling');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (121,'Érica Viana','movimento maker');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (122,'Erika Laíse','design thinking aplicado a planejamento de comunicação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (123,'Estela Rocha','Python');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (124,'Etienne Du Jardin','Arduino');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (125,'Fabiana Rocha Batista','Mulheres na Tecnologia e Ciência');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (126,'Fabiany Lima','Lógica de Programação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (127,'Fernanda Bernardo','unix');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (128,'Fernanda Campagnucci','infraestrutura');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (129,'Fernanda Lobato','Edutech');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (130,'Fernanda Mano','Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (131,'Fernanda Nascimento','Android');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (132,'Fernanda Nogueira','Python');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (133,'Fernanda Trindade Monteiro','Mineração/Análise de dados');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (134,'Flávia Dias Fortes','Grafos');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (135,'Francieli Viane','Comunidades');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (136,'Francine Micheli','Mulheres na Computação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (137,'Gabriela Galves Nunes','Direito digital');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (138,'Geisa Santos','negócios digitais');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (139,'Germanda Uchoa','Varejo Digital');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (140,'Giana de Almeida Pereira','Atendimento ao Cliente');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (141,'Gica Trierweiler Yabu','SAC 2.0');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (142,'Gina Gotthilf','Projetos Digitais');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (143,'Giovana Penatti','Inovação Social');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (144,'Gisele Késsia Gusmão Bizerril Gelschleiter','Feminismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (145,'Gisleine Silveira','Gestão de Equipes');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (146,'Grazielle Mendes Rangel','Branding Digital');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (147,'Halina Medina','Empreendedorismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (148,'Hanna Pereira','Marketing Digital');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (149,'Haydée Svab','Criação de conteúdo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (150,'Helena Margarido','Pitch Training');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (151,'Hendy Almeida','Financiamento Coletivo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (152,'Hevlin Costa','Computação em Nuvem');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (153,'Iaci Gomes','Sistemas Distribuídos');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (154,'Isabella Silveira','Back-End');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (155,'Ingrid Mantonavi','Startups');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (156,'Ivanise Gomes','Front-end');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (157,'Izadora Ribeiro Perkoski','Outreachy program');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (158,'Izza Simões','Software livre');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (159,'Jacqueline Yumi Asano','Python');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (160,'Janine Saponara','Machine Learning');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (161,'Janynne Gomes','Data Science');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (162,'Jeliel Mendes','Open Source');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (163,'Jennifer Payne','Ruby');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (164,'Jessica Temporal','Rails');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (165,'Jessilanny Nóbrega','Front-end');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (166,'Josilene Santana','Software Development');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (167,'Joviane Jardim','Empreendedorismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (168,'Juciellen Cabrera','RH');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (169,'Juily Manghirmalani','Treinamento e consultoria empresarial');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (170,'Júlia Albuquerque','Desenvolvimento de equipes');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (171,'Julia Stateri','Modelagem de negócio');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (172,'Juliana de Bittencourt Escobar','Organização de fluxos e processos');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (173,'Juliana Carvalho','Pesquisas empresariais e organizacionais');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (174,'Juliana Chahoud','Mobile Advertising');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (175,'Juliana Félix Nunes','Diversidade');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (176,'Juliana Fernandes','Inclusão');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (177,'Juliana Fernandes','LGBT Rights');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (178,'Juliana Guerra','Propaganda');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (179,'Juliana Hercowitz','Desenho de Moda');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (180,'Juliana Wallauer','Comidas Orgânicas');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (181,'Juliene Alves','Front-end');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (182,'Julyane Miranda','Comunidade');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (183,'Karen Figueiredo','Acessibilidade');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (184,'Karina Girardi Roggia','Product Management');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (185,'Karina Martins','Agile');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (186,'Karla Patriota Bronsztein','Scrum');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (187,'Kathlen Amado','Lean');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (188,'Kelly Kiyumi','Machine Learning');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (189,'Krystal Campioni','Python');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (190,'Laís Carvalho','Javascript');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (191,'Lais de Lima','Análise de Dados');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (192,'Larissa Sá','Visualização de Dados');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (193,'Laura Gurgel','R');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (194,'Laura Nobrega','Agile Analytics');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (195,'Letícia Passarelli Canova','Empreendedorismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (196,'Leticia Figueira','BigData');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (197,'Letícia Millião','Comunidades');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (198,'Letícia Motta','Mulheres na Computação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (199,'Leticia Portella','Impressora 3D');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (200,'Leticia Pozza','negócios sociais');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (201,'Letticia Nicoli','Ruby');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (202,'Lhaís Rodrigues','Rails');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (203,'Lidiane De Souza Monteiro','Coaching');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (204,'Lígia Bernar','Agilidade');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (205,'Lígia Zeppelini','Agile Coach');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (206,'Liliam Leal','Liderança');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (207,'Lilian Gonçalves','Facilitação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (208,'Lina Garrido','WordPress');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (209,'Lisi Moraes','Web Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (210,'Loiane Groner','Interatividade');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (211,'Luana Weitzel','Evangelizadora Joomla');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (212,'Luciana Guerra','Web engineer');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (213,'Luciana Minev','Consultora em FOSS');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (214,'Luciana Stabile','Desenvolvimento e participação das mulheres no mercado de games (impacto nacional e mundial)');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (215,'Luiza Guerra','Inbound PR');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (216,'Macarena Garcia','Personas');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (217,'Maitê Balhester','Relações Públicas Digitais');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (218,'Marcela Costa','Inbound Marketing');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (219,'Marcela Milano','Testes de Software');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (220,'Marcela Oliveira','Automação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (221,'Marcela Santos','Qualidade de software');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (222,'Márcia Santos Almeida','Varejo de moda');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (223,'Maria Clara Santana','Visual Merchandasing');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (224,'Marina Miranda','Criatividade e inovação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (225,'Mariana Araujo Mioto','Educação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (226,'Mariana Camargo','Canvas');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (227,'Mariana Gomes','Inteligência Artificial');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (228,'Mariana Janeiro','Mineração de dados');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (229,'Mariana Maneira','Rails');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (230,'Mariana Matos','R');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (231,'Marianne Costa','Machine Learning');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (232,'Mariela Castro','Testes de Software');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (233,'Marina Arilha Silva','Lean');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (234,'Maristela Moura','Agile');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (235,'Marta Preuss','Rails');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (236,'Marla Dore','Ruby');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (237,'Martina Scherrer','Cucumber');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (238,'Mayara Carolina de Paula','UX');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (239,'Mayara Miranda','Engenharia de Software');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (240,'Mayra Fonseca','Eletrônica');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (241,'Mayra R Souza','Gestão de Projetos');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (242,'Maysa de Oliveira','Games');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (243,'Meli Malatesta','Tecnologia');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (244,'Melissa Devens','Web');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (245,'Michele Costa','Conteúdo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (246,'Michelle Guimarães','Rádio e TV');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (247,'Mila Paes Leme Marques','Edição de Vídeos');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (248,'Mimi Newton','UX Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (249,'Mirian Meliani Nunes','Mulheres na Tecnologia');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (250,'Mônica Bulgari','Golang');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (251,'Mychelle Jacob','Python');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (252,'Myrian Connor','Data Science');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (253,'Nadezhda Bezerra Batista','Leadership');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (254,'Nádia Rebouças','Angular');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (255,'Natália Menhem','JS');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (256,'Natascha Hun','Fullstack Development');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (257,'Natasha Romariz','Segurança em Aplicações Web');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (258,'Nathalia Novaes Leonessa','Front-end');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (259,'Nathalia Sautchuk Patrício','Web Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (260,'Nessa Rodrigues','Wordpress');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (261,'Olivia Janequine','Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (262,'Paola Tucunduva','UX');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (263,'Patricia Almeida Ferreira','Empreendedorismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (264,'Patricia Arruda','Rails');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (265,'Patricia de Paula','Ruby');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (266,'Patricia Kouzmine','Back-end');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (267,'Patricia Ramos de Quadros','Product Management');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (268,'Patrícia Ribeiro','Leadership');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (269,'Patrícia Sant''Anna','Growth Hacking');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (270,'Paula Diniz','Entrepreneurship');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (271,'Paula Faria','Venture Capital');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (272,'Paula Grangeiro','Agile');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (273,'Paula Quintão','Negócios digitais');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (274,'Paulinha Paz','Gastronomia');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (275,'Preta Emmeline','economia compartilhada');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (276,'Priscila Chagas','Conteúdo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (277,'Rafaela Marques','SEO');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (278,'Rafaella Cavalca','Liderança Feminina');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (279,'Raissa dos Santos Ferreira','Gênero & Inovação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (280,'Raissa Klain Belchior','Empreendedorismo Feminino');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (281,'Raquel Camargo','Gênero & Tecnologia');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (282,'Raquel de Oliveira Santos Lira','Branding');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (283,'Raquel Prado','UX');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (284,'Raquel Preto','Startup');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (285,'Raquel Santachiara','Design Thinking');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (286,'Rayanny Nunes','Web Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (287,'Reimy Solange Chagas','Gestão de Projetos');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (288,'Renata Machado Tárrio','Gestão de Pessoas');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (289,'Renata Masseroni','Operações');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (290,'Rebeca Bordini','Processos');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (291,'Rebeca Serpa','Motivação');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (292,'Rita Lino','Comunicação Interna');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (293,'Robertta Mota','Inteligência Digital');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (294,'Ronaiza Cardoso','Atendimento');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (295,'Rosália Cipriano Oliveira','Desenvolvimento Web');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (296,'Rosi Rodrigues','Mídias Sociais');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (297,'Rosicléia Frasson','Web Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (298,'Rute Faria','Social Media Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (299,'Samanta Cicilia','Desenvolvimento de software');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (300,'Samantha Rosa','Agilidade');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (301,'Samira Almeida','Entrega e integração contínua');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (302,'Sandy Maciel','Empoderamento feminino');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (303,'Silvana Bahia','Empreendedorismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (304,'Silvia Helena Rocha Campos','Sexualidade');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (305,'Silvia Valadares','Feminismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (306,'Simone Amorim','Direitos Humanos');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (307,'Simone Pittner','Questões de Gênero');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (308,'Soraia Lima','Maternidade');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (309,'Stella Dauer','Social Media');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (310,'Suzana Bueno','Jornalismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (311,'Suzana Cohen','Finanças');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (312,'Tais Oliveira','Empreendedorismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (313,'Talita Lombardi','Produção de Conteúdo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (314,'Talita Pagani','Web');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (315,'Talita Rossari','Data on the Web');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (316,'Tancicleide Gomes','Open Data');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (317,'Tatiana Assali','Open Government');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (318,'Tatiana Lourenço','International Relations');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (319,'Tatiana Pezoa','Feminismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (320,'Tatiana Tosi','Marketing Digital');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (321,'Tatiana Vargas Maia','Mídias Sociais');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (322,'Tatiane Conceição Vergueiro','PHP');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (323,'Tatti Maeda','Front-end');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (324,'Tayra Vasconcelos','Back-End');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (325,'Thais Gentile','Front End');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (326,'Thais Godinho','Analista SEO');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (327,'Thais Moura de Freitas','Especialista em Joomla e Consultoria WEB');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (328,'Thais Souza','Análise de negócios');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (329,'Thaisa Mirely','Modelagem de dados');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (330,'Thaise Saeter','Desenho de processos');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (331,'Thalita Nick Pinheiro','Liderança de equipes');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (332,'Thaty Moura','Front-end');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (333,'Uafa Smaili','Back-end');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (334,'Valéria Barros','Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (335,'Vanessa Gonçalves Ferreira','Mobile');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (336,'Vanessa Kukul','Controle de Versão');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (337,'Vanessa Me Tonini','Jornalismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (338,'Vanessa Queiroz','Empreendedorismo');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (339,'Vanessa Rocha','Conteúdo Digital');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (340,'Vera Cristina de Moraes','Conteúdo para marcas');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (341,'Vivian Vianna','Design');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (342,'Viviane Vilella','Sustentabilidade');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (343,'Yanne Moreira','Economia criativa');
INSERT INTO mytable(FIELD1,Nome,TEMAS_DE_INTERESSES) VALUES (344,'Yasodara Córdova','Coaching');
