CREATE TABLE mytable(
   FIELD1      INTEGER  NOT NULL PRIMARY KEY 
  ,Nome        VARCHAR(42) NOT NULL
  ,Foto        VARCHAR(112) NOT NULL
  ,Localização VARCHAR(57) NOT NULL
);
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (0,'Adriana Antunes','./Mulheres Palestrantes_files/tumblr_n8g0ld4jND1tfojqwo1_1280.jpg','Caxias do Sul/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (1,'Adriana da Rosa Amaral','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAqwAAAAJDE0YmE0MmIxLWM5NjMtNDQ5MC05M2FjLWNjMDFjOGU5NzA1Zg.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (2,'Alda Rocha','./Mulheres Palestrantes_files/07ac697bcff40050a82cb4503de9eb68.png','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (3,'Alessandra Guglieri','./Mulheres Palestrantes_files/0ccfeff.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (4,'Alice Coutinho','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (5,'Aline de Campos','./Mulheres Palestrantes_files/AlinedeCampos.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (6,'Aline M. C. Freitas','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAYFAAAAJDVkMzNjY2U2LTNjMGQtNDE5NC1hNDgxLTBmM2RhY2MyYjBiNQ.jpg','Belém/PA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (7,'Aline Pêgas','./Mulheres Palestrantes_files/profile.jpg','Curitiba/PR');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (8,'Alline Jajah','./Mulheres Palestrantes_files/allinejajah-1418015868_280.jpg','Goiânia/GO');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (9,'Alline Oliveira','./Mulheres Palestrantes_files/26e9188.jpg','São Paulo/SP, Rio de Janeiro/RJ, Brasília/DF e Goiânia/GO');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (10,'Alynne Cid','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAcsAAAAJDc5ODNjOTU3LWE5MjItNGZjNi04ZjJkLTYwODJlYjU3OWYyNw.jpg','Belém/PA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (11,'Amanda Santana','./Mulheres Palestrantes_files/b1888a06cb886303500bc65c1d81f200.jpeg','Aracaju/SE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (12,'Amanda Silva Vieira','./Mulheres Palestrantes_files/ff491a846bf9e5f3f5d081787ff54ae2.jpeg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (13,'Amanda Vilela','./Mulheres Palestrantes_files/3ab1d4a265ad9289afe10956a78271df.jpeg','Sorocaba/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (14,'Amanda Zacarias Marinho','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAigAAAAJDc4Y2E4ZjUyLTVhYzAtNDgxNi05YTk0LWZhY2M5OWQ1Y2MzNA.jpg','Belo Horizonte/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (15,'Amélia Pessoa','./Mulheres Palestrantes_files/9038852','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (16,'Ana Antar','./Mulheres Palestrantes_files/ts6SYp9G_400x400.jpg','Salvador/BA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (17,'Ana Barcellos','./Mulheres Palestrantes_files/8314551','Brasília/DF');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (18,'Ana Carolina Alves Rodrigues','./Mulheres Palestrantes_files/0b16903eeb7899542ce526c21eee7c74.jpeg','Florianópolis/SC');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (19,'Ana Clarissa','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAMDAAAAJDRiZDJjMDczLWE5MWMtNGU0Yi04ZTc4LTk5NjU2M2VmNTlmNQ.jpg','Manaus/AM');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (20,'Ana Del Mar','./Mulheres Palestrantes_files/0_pIHHOU-J17PpZDyH.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (21,'Ana Fontes','./Mulheres Palestrantes_files/AAIAAgDGAAAAAQAAAAAAAAmTAAAAJDY4MGJhMGI5LTBhNmEtNDU4Yi04ZWVlLWE1ZjFhNzdlODNmZg.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (22,'Ana Julia Ghirello','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAhkAAAAJDc3MjI1MDk3LWFiMDctNDNlYi1iYmJhLTEwYjA3NTBkNGVmOA.jpg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (23,'Ana Luíza Avellar','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAgUAAAAJGI2MjVlZjQwLTQzMzAtNDE3Zi1hZGQ1LWRmZGI5NmEzNzE1NA.jpg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (24,'Ana Luiza Bastos','./Mulheres Palestrantes_files/10088900','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (25,'Ana Paula Coelho Barbosa','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAi8AAAAJGM4ZDM3NDk0LTcxNmEtNDBjYy1hODFlLWQ0Yzg0ZmViMjUxMA.jpg','Ilhabela/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (26,'Ana Paula da Silva Mendes','./Mulheres Palestrantes_files/27858278_2471054366452191_7904831545054840493_n.jpg','Teresina/PI');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (27,'Ana Paula de Luca','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (28,'Ana Paula Gaspar','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (29,'Ana Paula Gomes','./Mulheres Palestrantes_files/38e1ead1b5834e26fb681116e6b7ebf5.jpeg','Belo Horizonte/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (30,'Ana Paula Marques','./Mulheres Palestrantes_files/placeholder-female.jpg','Sobral/CE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (31,'Ana Paula Vargas Maia','./Mulheres Palestrantes_files/AAIAAgDGAAAAAQAAAAAAAAxkAAAAJGJmYTRmMzUzLWYzYjYtNDQ2ZS04MWM3LTAxMjIxZTVhMGJlOA.jpg','Salvador/BA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (32,'Ana Raquel Calháu Pereira','./Mulheres Palestrantes_files/5718645','Itajubá/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (33,'Ana Ribeiro','./Mulheres Palestrantes_files/fbcae7dfc50e5e33d18cae175d957c64.jpeg','Campina Grande/PB');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (34,'Ana Rute Mendes','./Mulheres Palestrantes_files/a4d2fe468c774392ea7deb9efb9e61f5.jpeg','São Paulo e Campinas/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (35,'Ana Schwendler','./Mulheres Palestrantes_files/I8PSmdIN.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (36,'Ananda Carvalho','./Mulheres Palestrantes_files/3c368abae57d0fb60ff976fb1be47d99','Manaus/AM');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (37,'Andrea Barberà','./Mulheres Palestrantes_files/AAIA_wDGAAAAAQAAAAAAAAquAAAAJDMzZTZlOTE4LWZmNTctNDUwMy05NzExLTI3ODQ2MDM1M2ExNg.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (38,'Andrea Siqueira','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAgXAAAAJGU1YmVlMjZmLWI4N2UtNGVlNi1iYzlhLWUyMjQ0YTA0YzI3ZQ.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (39,'Andrea Schostack','./Mulheres Palestrantes_files/qvDU2DKf.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (40,'Andréa Zambrana','./Mulheres Palestrantes_files/400922','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (41,'Andressa Chiara','./Mulheres Palestrantes_files/ca79853a5595723513d7da6caf13c94e.jpeg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (42,'Andressa Sivolella','./Mulheres Palestrantes_files/272868','Rio de Janeiro/RJ e');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (43,'Andreza Leite','./Mulheres Palestrantes_files/19ffbedf91fda0d0bc3f72d719902d66.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (44,'Anielle Guedes','./Mulheres Palestrantes_files/placeholder-female.jpg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (45,'Anna Cruz','./Mulheres Palestrantes_files/0afb5c6c63c9e0ce7666528524ed6727.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (46,'Annelise Gripp','./Mulheres Palestrantes_files/6d3f646a5629bc5e23a73cec15cb4975.jpeg','Rio de Janeiro/RJ e São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (47,'Anyssa Ferreira','./Mulheres Palestrantes_files/anyssaferreira-296x300.jpg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (48,'Ariadne Pinheiro','./Mulheres Palestrantes_files/1ccd5f673dc4ab769c25180b5b4da5e1.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (49,'Ariane Parra','./Mulheres Palestrantes_files/416a736d3a63450abc19b91bbb7ce64b','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (50,'Ariane Feijó','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAm0AAAAJDVlYjAxMDI5LWNjMTgtNGQxMy1hNjZkLWEyMTY0YWIyNDVkZA.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (51,'Ariane Izac','./Mulheres Palestrantes_files/14958fc6544edc07d96d33d6b6ba6a0b.jpeg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (52,'Ariela Ranielly de Paula Silveira','./Mulheres Palestrantes_files/33342fd.jpg','Campinas/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (53,'Augusta Guta Orofino','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (54,'Bárbara Barbosa','./Mulheres Palestrantes_files/763533','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (55,'Bárbara Cabral','./Mulheres Palestrantes_files/b0bf5ac8e0adfef3bd50004203ef9df7.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (56,'Bárbara Dariano Silva Suzuki','./Mulheres Palestrantes_files/e0914b23096ad6b2c4f16ae206f20b90.jpeg','Florianópolis/SC');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (57,'Barbara Jacinto','./Mulheres Palestrantes_files/photo.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (58,'Bianca Brancaleone','./Mulheres Palestrantes_files/HZdoLbi9.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (59,'Bianca Rosa','./Mulheres Palestrantes_files/63ddf8a769ed56c72f36a35c85b5d337.jpeg','Sorocaba/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (60,'Bianca Marques','./Mulheres Palestrantes_files/17528956','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (61,'Cah Felix','./Mulheres Palestrantes_files/5debfa9b1fb78885f4e8df4915cb425f.jpeg','Salvador/BA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (62,'Camila Achutti','./Mulheres Palestrantes_files/2078347','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (63,'Camila Campos','./Mulheres Palestrantes_files/2309096','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (64,'Camila Ferreira','./Mulheres Palestrantes_files/691624a81373dd9da912e1bda573fe10.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (65,'Camila Godoy','./Mulheres Palestrantes_files/placeholder-female.jpg','Florianópolis/SC');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (66,'Camila Haddad','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (67,'Camila Petry Feiler','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (68,'Carine Roos','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAgtAAAAJGUyZWNhODE0LTIzMTQtNDhmOC05ZWQ5LWE0ZjZhOWViNzEwMg.jpg','Curitiba/PR');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (69,'Carla de Bona','./Mulheres Palestrantes_files/AAEAAQAAAAAAAA26AAAAJGRmMjg4ZDA5LWEzYmYtNGZkOS1iZDM0LWI1ODVmNDMwYTgwZA.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (70,'Carla Moranga','./Mulheres Palestrantes_files/AAEAAQAAAAAAAArhAAAAJDI2MmY3NDU0LTQxZTItNDAyZC05MzQwLTFjMWE5NmRiMzU1Ng.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (71,'Camila Waz','./Mulheres Palestrantes_files/AAEAAQAAAAAAAArfAAAAJGQyNzA4NDQ1LTI2YjEtNGQ0NS1hOGU3LWY5MzU3Zjk0OWViOA.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (72,'Camilla Falconi Crispim','./Mulheres Palestrantes_files/5ed936f516df3562fe20b3a1338e7fb5.jpeg','João Pessoa/PB');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (73,'Carol Aguiar','./Mulheres Palestrantes_files/placeholder-female.jpg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (74,'Carol Patrocínio','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAedAAAAJDhjYzVjYTIxLTU1ZTMtNDQzNy05YmVhLTUwYTcwZDdmNjNhMw.jpg','Curitiba/PR');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (75,'Carolina Ruhman Sandler','./Mulheres Palestrantes_files/mini-carolina.png','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (76,'Caroline Burle','./Mulheres Palestrantes_files/6430260','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (77,'Celine Ramos','./Mulheres Palestrantes_files/i114D6dv_400x400.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (78,'Chaiane Simmler','./Mulheres Palestrantes_files/2c5fdc63b557f2588138056240fba94e','Salvador/BA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (79,'Cíntia Mara','./Mulheres Palestrantes_files/f4d05fff206f059c2c5925df8dbf1bdb.jpeg','Itajaí/SC');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (80,'Clara Verena Battesini','./Mulheres Palestrantes_files/8d7d0c819f2b46610e81cecf0a122c8f','Belo Horizonte/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (81,'Clarissa Barreto','./Mulheres Palestrantes_files/24b4c5a.jpg','Salvador/BA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (82,'Clarissa Sóter','./Mulheres Palestrantes_files/9be3ac92a937615d8547ceec4072f177','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (83,'Claudia Carolina Boletti','./Mulheres Palestrantes_files/96289319fa2117a461d6cfbfbf3910cf.jpeg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (84,'Claudia Peruzzato','./Mulheres Palestrantes_files/AAEAAQAAAAAAAASIAAAAJDM2NDA0NjU0LTljMWEtNGQ1OS1hMGMyLWRkYjYyYzJhMTNkMg.jpg','São Bernardo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (85,'Conceição Morais','./Mulheres Palestrantes_files/7e8715a92e543bffbd9c1d41872ab06b','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (86,'Cynthia Torchi','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAWbAAAAJDkxM2EyMmU2LTNmYzctNDQ4MC05MWI5LWIzZmE3ZDBhZTk0Yg.jpg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (87,'Cynthia Tscha','./Mulheres Palestrantes_files/placeholder-female.jpg','Taubaté/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (88,'Cynthia Zanoni','./Mulheres Palestrantes_files/acf2c97fd68b165d50bdf8f446afc0e7.jpeg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (89,'Cristal Bittencourt','./Mulheres Palestrantes_files/0d6bb01b9265417c64fd97c6fb19bc7c.jpeg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (90,'Daiany Maia de Andrade','./Mulheres Palestrantes_files/AAIAAgDGAAAAAQAAAAAAAAwtAAAAJDY1OWQ1ZGIwLTEwNGMtNDllMS04ODhlLTA4YjQzMGQyYjY3NQ.jpg','Salvador/BA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (91,'Dalianny Vieira','./Mulheres Palestrantes_files/13053265','Ribeirão Preto/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (92,'Daniela Araújo','./Mulheres Palestrantes_files/d0527f5a78b2e1575ccd9da7522a41c1.jpeg','Salvador/BA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (93,'Daniela Bertocchi','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAxYAAAAJGYwNjlmMDcyLTdkMGYtNDM1OC1hYWEyLTA1YzdmMmUzZjIxOQ.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (94,'Daniela Castilho Schwab','./Mulheres Palestrantes_files/cf45e10a82c4f4638863f6d856df9ca2.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (95,'Daniela Feitosa','./Mulheres Palestrantes_files/0bd72ea.jpg','Campinas/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (96,'Daniela Palumbo','./Mulheres Palestrantes_files/23b588ae707121505f5bcdedb8095227.png','Salvador/BA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (97,'Daniela Petruzalek','./Mulheres Palestrantes_files/4bb860bd1c186becbfb64a5a40d8ee19.jpeg','Campinas/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (98,'Daniela Senador','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAZAAAAAJGJjOWQ1OGJjLWM1MjYtNDg2My05MjlmLWQ0ZmJlODliNzg2ZA.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (99,'Daniela Victorazzi','./Mulheres Palestrantes_files/AAEAAQAAAAAAAA2WAAAAJGViNDJjZjgyLWIwN2MtNGE1OC1iYzQxLTI5OTcwM2U3ZGEzNA.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (100,'Daniele Andrade','./Mulheres Palestrantes_files/16c4248354041b76f72da23d755d6b7b','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (101,'Daniele Zandoná','./Mulheres Palestrantes_files/placeholder-female.jpg','Fortaleza/CE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (102,'Danielle Teixeira','./Mulheres Palestrantes_files/5931990','Campinas/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (103,'Danielle Vieira','./Mulheres Palestrantes_files/AAMAAgDGAAwAAQAAAAAAAAsAAAAAJDM2ZjVjZGU0LTRkNjUtNDk2YS1hZWY3LTdiZjQ4ZGYyM2M3Yg.jpg','Lauro de Freitas/BA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (104,'Dayany Espíndola','./Mulheres Palestrantes_files/02582cea45d1ed66154b355aa1dc696d.jpeg','Sorocaba/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (105,'Deb Xavier','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAvoAAAAJGY2ZjM4NGQ1LWRjNTQtNDZiYy1hNWYyLTdhYTBjMDZmMzMwMg.jpg','Rio de Janeiro/RJ e São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (106,'Déia Zoboli','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (107,'Deise Lima','./Mulheres Palestrantes_files/placeholder-female.jpg','Joinville/SC');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (108,'Denise Pagnussat','./Mulheres Palestrantes_files/3b13bc0.jpg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (109,'Denise Teófilo','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAhBAAAAJDJjNzE0YjE0LThjMjktNDZmNC1hMmViLTA2NWNmNzdhNGUwMg.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (110,'Diana Arnos','./Mulheres Palestrantes_files/4ce43cd2535d0afe50065a743af646e9.jpeg','Sorocaba/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (111,'Diane Lima','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAI8AAAAJDc2NTczNDQ4LWY3ZDctNGJhZC04NTkwLWQ4NTAyNWU3MDBiMw.jpg','Osasco/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (112,'Elisa Carlos Pereira','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (113,'Elis Forgerini','./Mulheres Palestrantes_files/AAEAAQAAAAAAAA03AAAAJDViNGYwODRlLWM3MWEtNDRiNi05Y2MxLTdmNDZmYjQ4Mzg3MQ.jpg','Jundiaí/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (114,'Elizabeth Regina Tscha','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (115,'Eluana Sievert Cardoso','./Mulheres Palestrantes_files/AAIA_wDGAAAAAQAAAAAAAAvQAAAAJDQ3M2Q1NDI5LTM2N2UtNDJiMi04NzQ4LWUwZTU3OTM0NWQ1MA.jpg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (116,'Emanuelle Menali','./Mulheres Palestrantes_files/0c019979ee02a71763ea2e44dd91e0bb.jpeg','Curitiba/PR');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (117,'Emmanuelle Richard','./Mulheres Palestrantes_files/cd920d13e1da5783e99a4372bc0f9fd2','Santa Luzia/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (118,'Erica Ariano','./Mulheres Palestrantes_files/AAMAAgDGAAwAAQAAAAAAAA8gAAAAJDIwNGYxNzVkLTMyOTctNGY5ZS1hNjgyLTM4YzI3MDVhYjllZA.jpg','Natal/RN');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (119,'Érica Calil Nogueira','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAVEAAAAJDNhZWIxNTYyLTgzMjYtNDc2ZS04MmE0LTA3NjVhYTE4MDc3NA.jpg','Santo André/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (120,'Erica Marques','./Mulheres Palestrantes_files/0b61b5ff9300a85587390e168845cbd4.jpeg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (121,'Érica Viana','./Mulheres Palestrantes_files/82a915535fb89f078db00ec645e05cc9','Curitiba/PR');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (122,'Erika Laíse','./Mulheres Palestrantes_files/0aaf2fe.jpg','Belo Horizonte/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (123,'Estela Rocha','./Mulheres Palestrantes_files/AAEAAQAAAAAAAApsAAAAJDEyY2RjNjMxLTFjMmMtNDMwYS1iMTU2LWEzNzQ3MzFmMGRlYw.jpg','Belo Horizonte/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (124,'Etienne Du Jardin','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAt8AAAAJGQ5MWY2OTkxLTczMDUtNDUyMi04OGM3LTBlZGY1ZTFmOGU3Yw.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (125,'Fabiana Rocha Batista','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (126,'Fabiany Lima','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (127,'Fernanda Bernardo','./Mulheres Palestrantes_files/393a8afb36c128e762e5130549d22dbe.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (128,'Fernanda Campagnucci','./Mulheres Palestrantes_files/0f196a83d85a2c66c3eb8678b3d96e7a.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (129,'Fernanda Lobato','./Mulheres Palestrantes_files/29c9108ca9fd4485e8b00858892bd0a5.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (130,'Fernanda Mano','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (131,'Fernanda Nascimento','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAuTAAAAJDAxMWM0MjExLWZkNmEtNDZkOC05YzAwLWM0ZmY5ODhhMmQ1NQ.jpg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (132,'Fernanda Nogueira','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (133,'Fernanda Trindade Monteiro','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (134,'Flávia Dias Fortes','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAnfAAAAJGZlNjI4MTM2LWM1YjQtNGExNy04NGFjLTBlNzM5ZWU1ZDc1Mg.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (135,'Francieli Viane','./Mulheres Palestrantes_files/1158ea2d0be5632609d067d2ebebacb9.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (136,'Francine Micheli','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAoYAAAAJDdiMTQxNzA0LWFmOTgtNDEwOC05OTVhLThkMzNhMmNkZTVhMQ.jpg','Belo Horizonte/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (137,'Gabriela Galves Nunes','./Mulheres Palestrantes_files/aa602dcc4ba2afe200d65b808f3d713f','Ribeirão Preto/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (138,'Geisa Santos','./Mulheres Palestrantes_files/5049246','Curitiba/PR');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (139,'Germanda Uchoa','./Mulheres Palestrantes_files/placeholder-female.jpg','Salvador/BA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (140,'Giana de Almeida Pereira','./Mulheres Palestrantes_files/14f078115953cf2ea31d9891ac083eeb.jpeg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (141,'Gica Trierweiler Yabu','./Mulheres Palestrantes_files/568119.53d90b133af39.jpg','Florianópolis/SC');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (142,'Gina Gotthilf','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (143,'Giovana Penatti','./Mulheres Palestrantes_files/AAMAAgDGAAwAAQAAAAAAAA0uAAAAJGNiMTU2YWVmLWVhZDEtNGJiMC04MDM2LTdkOWI4OGU5ZWEwNA.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (144,'Gisele Késsia Gusmão Bizerril Gelschleiter','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (145,'Gisleine Silveira','./Mulheres Palestrantes_files/41052_1241696062527_7336928_n.jpg','Aracaju/SE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (146,'Grazielle Mendes Rangel','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAXIAAAAJDVkZDE0YTVkLTkxNmYtNDRjZC04OTljLTNhOWQ5OThjYjNmMA.jpg','Montreal/Canadá');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (147,'Halina Medina','./Mulheres Palestrantes_files/AAMAAQDGAAwAAQAAAAAAAAvyAAAAJGU2Zjg1NzU1LTY4MjMtNDI4NS04MTlhLTJhOTJmNzc0MmJmZg.jpg','Belo Horizonte/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (148,'Hanna Pereira','./Mulheres Palestrantes_files/92f91622d6f40aee53dae82376a1b725','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (149,'Haydée Svab','./Mulheres Palestrantes_files/96b81d9c691891f599a9c35dcbb412f0.png','São Vicente/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (150,'Helena Margarido','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (151,'Hendy Almeida','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (152,'Hevlin Costa','./Mulheres Palestrantes_files/a3a83c902112cedccc0e071147027a72.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (153,'Iaci Gomes','./Mulheres Palestrantes_files/AAMAAQDGAAwAAQAAAAAAAA6mAAAAJDY5ZmJlZWVhLTRmMWUtNGFjNS1iMTljLWMxYTE4OGYzM2ZmNQ.jpg','Jundiaí/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (154,'Isabella Silveira','./Mulheres Palestrantes_files/4542747','Belém/PA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (155,'Ingrid Mantonavi','./Mulheres Palestrantes_files/018be55.jpg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (156,'Ivanise Gomes','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAg_AAAAJGYyMmM0NzM1LTEyZGYtNDFkMC04MmMwLTI5NTE5ZmM5OWQxMw.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (157,'Izadora Ribeiro Perkoski','./Mulheres Palestrantes_files/b58009e9c7a0dee56bfb552e58f69ca8.jpeg','Campinas/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (158,'Izza Simões','./Mulheres Palestrantes_files/AAMAAgDGAAwAAQAAAAAAAA5AAAAAJDRkZWIyZTA3LTg3ZTctNGNiZi04ODhlLTY2NGZiYTdjYjNhMQ.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (159,'Jacqueline Yumi Asano','./Mulheres Palestrantes_files/24320336','João Pessoa/PB');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (160,'Janine Saponara','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAvoAAAAJDgxMDczMjgwLWUwOTYtNDI1MS1hYzRlLThlYjU1ZTM5NTMzMg.jpg','Florianópolis/SC');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (161,'Janynne Gomes','./Mulheres Palestrantes_files/AAMABADGAAwAAQAAAAAAAAoJAAAAJDEzNTE5YjY4LTBhMzEtNDcyNC04YWIwLTgxNTU2NDdkYWQ0Yg.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (162,'Jeliel Mendes','./Mulheres Palestrantes_files/4261484','Governador Valadares/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (163,'Jennifer Payne','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (164,'Jessica Temporal','./Mulheres Palestrantes_files/35beca46843e4adcbd43df1bc93ce38b.jpeg','Blumenau/SC');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (165,'Jessilanny Nóbrega','./Mulheres Palestrantes_files/placeholder-female.jpg','Osasco/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (166,'Josilene Santana','./Mulheres Palestrantes_files/placeholder-female.jpg','Campina Grande/PB');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (167,'Joviane Jardim','./Mulheres Palestrantes_files/2b1269b.jpg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (168,'Juciellen Cabrera','./Mulheres Palestrantes_files/0b8df4309d2e40efce1208242c35a058','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (169,'Juily Manghirmalani','./Mulheres Palestrantes_files/AAIAAgDGAAAAAQAAAAAAAA1PAAAAJGI3YTM0ZGI2LTI4ODItNGY1OS04Y2VkLWZkYWJiOTBiZmVmOA.jpg','Guarulhos/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (170,'Júlia Albuquerque','./Mulheres Palestrantes_files/fb39d8165fcc2edf3375d0eba8b0d6ff.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (171,'Julia Stateri','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAjwAAAAJDkzYmFkMTU3LTYwNjUtNDFlOC04NWVhLTRiMDZjZTU0ZTlkZg.jpg','Maceió/AL');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (172,'Juliana de Bittencourt Escobar','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAjqAAAAJGNkYjM1YTgzLTYxMzItNDkyMC1iNGUxLWJjMjBiYzg0YmNlMA.jpg','Campinas/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (173,'Juliana Carvalho','./Mulheres Palestrantes_files/AAMABADGAAwAAQAAAAAAAA6zAAAAJGRjMGVhYmE3LTQ5ZTgtNGU3Yy04NTJkLTQ5NTU2NjJlNDllOA.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (174,'Juliana Chahoud','./Mulheres Palestrantes_files/placeholder-female.jpg','João Pessoa/PB');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (175,'Juliana Félix Nunes','./Mulheres Palestrantes_files/3291727','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (176,'Juliana Fernandes','./Mulheres Palestrantes_files/037d35f865f95571c3194b4c84a4915b.jpeg','Goiânia/GO');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (177,'Juliana Fernandes','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (178,'Juliana Guerra','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAviAAAAJGFhMzc0MDFiLWZjNTAtNDE1YS1hZGE2LWYxMjU3MTRkZWJmMg.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (179,'Juliana Hercowitz','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAd8AAAAJDc0MTdjYWJjLWQxYTMtNGQ1NS1hNDQxLWIwZjAxNmZmZjhmMA.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (180,'Juliana Wallauer','./Mulheres Palestrantes_files/AAIA_wDGAAAAAQAAAAAAAAxxAAAAJDc0NTMyMGNmLWI3MGUtNGRlOC05ZGEwLWI1MGYzMjkzODkwOQ.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (181,'Juliene Alves','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAl0AAAAJDM1OWFmZTI2LTM0OTQtNDMwMy1hN2Q2LTUyODgzNjg5YTNhZg.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (182,'Julyane Miranda','./Mulheres Palestrantes_files/APVpL4L6_400x400.jpg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (183,'Karen Figueiredo','./Mulheres Palestrantes_files/ad74bd0e6c00310471c4761e1ec73f5d','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (184,'Karina Girardi Roggia','./Mulheres Palestrantes_files/5774b104265c725d9ea7e65b5411a2c2.jpeg','Cuiabá/MT');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (185,'Karina Martins','./Mulheres Palestrantes_files/placeholder-female.jpg','Joinville/SC');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (186,'Karla Patriota Bronsztein','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (187,'Kathlen Amado','./Mulheres Palestrantes_files/3bae151.jpg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (188,'Kelly Kiyumi','./Mulheres Palestrantes_files/82810bb4e5c8a9caecda9f48ed285ffc.jpeg','Brasília/DF');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (189,'Krystal Campioni','./Mulheres Palestrantes_files/891f39aa823d65aed365e0b801a58af8.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (190,'Laís Carvalho','./Mulheres Palestrantes_files/2b1fd1c.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (191,'Lais de Lima','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAROAAAAJDdiM2Q2ZGMyLWY5NGUtNDUxOC1iZmRmLWE0MGEyNDdhOTE4Mg.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (192,'Larissa Sá','./Mulheres Palestrantes_files/55ea4b542e9aef1c4cfc45e30100b9a9','Belém/PA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (193,'Laura Gurgel','./Mulheres Palestrantes_files/placeholder-female.jpg','Brasilia/DF');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (194,'Laura Nobrega','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAeOAAAAJDY0Yzc1ZDk4LTExYTItNGJkZS1hNWViLTAxZWQyYTllNjQwMw.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (195,'Letícia Passarelli Canova','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (196,'Leticia Figueira','./Mulheres Palestrantes_files/a47dc8cc9354985bd4f688c78e910261.png','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (197,'Letícia Millião','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAmJAAAAJDJkMDQ1YzQ0LThhZGEtNGZiNS1hMjdkLTIwNmJjMDFhZTc2MA.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (198,'Letícia Motta','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAlHAAAAJDAyMDMwNjkwLWMxNTYtNDIyYy1iYzYxLWRjOGM0MmQzMjI3NA.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (199,'Leticia Portella','./Mulheres Palestrantes_files/96f6148ae5af63f90246a3817686b457.jpeg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (200,'Leticia Pozza','./Mulheres Palestrantes_files/0ce2411.jpg','Ribeirão Preto/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (201,'Letticia Nicoli','./Mulheres Palestrantes_files/13442773','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (202,'Lhaís Rodrigues','./Mulheres Palestrantes_files/171d49d996b7c9c2d93af7066948dc47.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (203,'Lidiane De Souza Monteiro','./Mulheres Palestrantes_files/b71e8a1577930c3d84478e5c325d5d53.jpeg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (204,'Lígia Bernar','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAwCAAAAJDljZGVjYTY5LWY3NWYtNDM5Yi1hYmExLTAyNDUwNmJlY2JjZg.jpg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (205,'Lígia Zeppelini','./Mulheres Palestrantes_files/7f92138973430327cc2a6c2758c31b15.png','Belém/PA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (206,'Liliam Leal','./Mulheres Palestrantes_files/da72818e353c00159b1e259359de6fe0','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (207,'Lilian Gonçalves','./Mulheres Palestrantes_files/16c4a29.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (208,'Lina Garrido','./Mulheres Palestrantes_files/08a9d15.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (209,'Lisi Moraes','./Mulheres Palestrantes_files/23afdd1.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (210,'Loiane Groner','./Mulheres Palestrantes_files/59545','Florianópolis/SC');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (211,'Luana Weitzel','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (212,'Luciana Guerra','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAs9AAAAJDEzMjhhMmY3LTBhZTMtNDYyMS1hNTI1LWNkNjZiMmViOWVhZA.jpg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (213,'Luciana Minev','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (214,'Luciana Stabile','./Mulheres Palestrantes_files/placeholder-female.jpg','Manaus/AM');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (215,'Luiza Guerra','./Mulheres Palestrantes_files/65c5b3ac0eeae6d90fea315e72068f16.jpeg','Ribeirão Preto/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (216,'Macarena Garcia','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAliAAAAJDZmZWIxM2RhLTJiM2MtNDIyZS04OTViLTc0NzI4YjA2OGY1Nw.jpg','Belo Horizonte/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (217,'Maitê Balhester','./Mulheres Palestrantes_files/7ee96fafef481d455a222c6102cf3528.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (218,'Marcela Costa','./Mulheres Palestrantes_files/placeholder-female.jpg','Santo André/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (219,'Marcela Milano','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAxHAAAAJGIwYjc2Mzc5LWM3MDAtNGM1NC04MTQyLTk4MDc2ZGNiMDE2ZQ.jpg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (220,'Marcela Oliveira','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAMzAAAAJGYwZjJjYmM1LTEzODktNDFmZS05YzFkLWE3ODUwN2FlNDcwYQ.jpg','Curitiba/PR');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (221,'Marcela Santos','./Mulheres Palestrantes_files/ac3d63657b5e83530e24cde0172776c0.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (222,'Márcia Santos Almeida','./Mulheres Palestrantes_files/67f4a42acf26552b0212c6fb6e4b186f.jpeg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (223,'Maria Clara Santana','./Mulheres Palestrantes_files/78b75aad21ed5ed351d9822d77acd7fc.jpeg','Goiânia/GO');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (224,'Marina Miranda','./Mulheres Palestrantes_files/placeholder-female.jpg','Maceió/AL');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (225,'Mariana Araujo Mioto','./Mulheres Palestrantes_files/acf4d17d0e0a7f8f0ba61f4d7895c489.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (226,'Mariana Camargo','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (227,'Mariana Gomes','./Mulheres Palestrantes_files/2fec6491815582734b1ddc97449a44a4','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (228,'Mariana Janeiro','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAkQAAAAJGZlMjFlZDM5LWJmY2ItNDYwMi04MzRmLTlkZWMwOTlmNjNkNw.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (229,'Mariana Maneira','./Mulheres Palestrantes_files/852d4d7999da6483617ca28da2383b4d.jpeg','Jundiaí/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (230,'Mariana Matos','./Mulheres Palestrantes_files/1b21abc.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (231,'Marianne Costa','./Mulheres Palestrantes_files/c2eae133a7e4c21231cb8e886497198c','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (232,'Mariela Castro','./Mulheres Palestrantes_files/4c2f1d898d747dab7585d050ac8273ca','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (233,'Marina Arilha Silva','./Mulheres Palestrantes_files/022ff18e9fba3f2db09f7e35f1c5c339','Curitiba/PR');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (234,'Maristela Moura','./Mulheres Palestrantes_files/1f18906.jpg','Jundiaí/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (235,'Marta Preuss','./Mulheres Palestrantes_files/901ef2fc184b347a5f5717c2ddc3f5e6.jpeg','Indaiatuba/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (236,'Marla Dore','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAMtAAAAJDMyZDY1Y2UyLTAxZWUtNDk2Ny1iODI1LWJjMmY4ODQ0NzFhZQ.jpg','Florianópolis/SC');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (237,'Martina Scherrer','./Mulheres Palestrantes_files/e3a29c667bd11908fe3006b90bc61619.jpeg','Salvador/BA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (238,'Mayara Carolina de Paula','./Mulheres Palestrantes_files/4465d8b13bc5825ffbe1ebea01cc7cc8','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (239,'Mayara Miranda','./Mulheres Palestrantes_files/10636124_932122716807075_2937596775672211091_n.jpg','Fortaleza/CE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (240,'Mayra Fonseca','./Mulheres Palestrantes_files/AAEAAQAAAAAAAA3HAAAAJDI0NGJiMTRkLTJjMmUtNDJkNy04YTdkLWRkNGUwNzZmMTc2ZA.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (241,'Mayra R Souza','./Mulheres Palestrantes_files/13318439','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (242,'Maysa de Oliveira','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAwGAAAAJGQxMGE3ZWNkLTgxNzUtNDA3My04ZDBkLWVjN2E2ZDE4OGUyNg.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (243,'Meli Malatesta','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAlvAAAAJDUyODNlMzE2LWRiNmMtNDUxYy1hNDA3LTZhMWNmMWUxN2U0MA.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (244,'Melissa Devens','./Mulheres Palestrantes_files/ad3b9541600ce3b1e57fdebfa6191c20.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (245,'Michele Costa','./Mulheres Palestrantes_files/placeholder-female.jpg','Campinas /SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (246,'Michelle Guimarães','./Mulheres Palestrantes_files/placeholder-female.jpg','Rolim de Moura/RO');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (247,'Mila Paes Leme Marques','./Mulheres Palestrantes_files/placeholder-female.jpg','Manaus/AM');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (248,'Mimi Newton','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAxVAAAAJDQyOTdjYzZiLTBlNmQtNDgwYS1iMmNmLTk3ZTc2YjM4MGY5MA.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (249,'Mirian Meliani Nunes','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (250,'Mônica Bulgari','./Mulheres Palestrantes_files/d0cee09c38060345dcdc63d055f0bc54.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (251,'Mychelle Jacob','./Mulheres Palestrantes_files/d4be3cb0a04673af6d875058c2c2effe','Campinas/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (252,'Myrian Connor','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAjGAAAAJDg2ZGU5MWIzLThkYWItNDkxMS1iYTk0LTdmZTA1OGFhMDIxMg.jpg','Olinda/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (253,'Nadezhda Bezerra Batista','./Mulheres Palestrantes_files/placeholder-female.jpg','Castanhal/PA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (254,'Nádia Rebouças','./Mulheres Palestrantes_files/AAIAAgDGAAAAAQAAAAAAAAmeAAAAJDBmZTY5NGExLTQxOTMtNDc2Yi1hOTkxLTY4OWI1MjUzYTkxZg.jpg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (255,'Natália Menhem','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAuTAAAAJDU1YmY3YTU1LTdmMmEtNDhmOS05OTFhLTk3M2E0NjczYjVmYQ.jpg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (256,'Natascha Hun','./Mulheres Palestrantes_files/60a21ab75db2e268aa55b2973e2f69c8','Belo Horizonte/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (257,'Natasha Romariz','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAh8AAAAJGYxZDdmZTZhLTFhZGQtNDZhNy04MDY2LTgwZTRmNjcyZjQ1ZA.jpg','Sorocaba/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (258,'Nathalia Novaes Leonessa','./Mulheres Palestrantes_files/aee3962dd39be56420d63161bb0c859c','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (259,'Nathalia Sautchuk Patrício','./Mulheres Palestrantes_files/ce31b72323ed84b80253f4340c98c9dd.png','Sorocaba/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (260,'Nessa Rodrigues','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAqnAAAAJDllZGQzNWVhLWUyMTQtNDJlNS05NGMxLTNlMjlkNWM1OWQ2Yw.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (261,'Olivia Janequine','./Mulheres Palestrantes_files/371e87d45d7e34a1ed6f82a665714106.jpeg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (262,'Paola Tucunduva','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (263,'Patricia Almeida Ferreira','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (264,'Patricia Arruda','./Mulheres Palestrantes_files/b909b45ac714b7e019b3e6c3c1623916','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (265,'Patricia de Paula','./Mulheres Palestrantes_files/a125fea1abff71dd443b09ba3918c482','União da Vitória/PR');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (266,'Patricia Kouzmine','./Mulheres Palestrantes_files/AAIA_wDGAAAAAQAAAAAAAAy7AAAAJGUwNTQxMGJkLTJmMmYtNDliMy05NGFmLTM5MjA3NTFmY2I3OQ.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (267,'Patricia Ramos de Quadros','./Mulheres Palestrantes_files/placeholder-female.jpg','Brasília/DF');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (268,'Patrícia Ribeiro','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (269,'Patrícia Sant''Anna','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAdHAAAAJDE5NDQxMTQ0LWU0M2YtNDQzOC1iZTQ4LWY1N2UwZTE0ODhkYw.jpg','Campinas/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (270,'Paula Diniz','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (271,'Paula Faria','./Mulheres Palestrantes_files/ed70023e19882637aef103170e81f365.jpeg','Belo Horizonte/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (272,'Paula Grangeiro','./Mulheres Palestrantes_files/2524981','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (273,'Paula Quintão','./Mulheres Palestrantes_files/placeholder-female.jpg','Manaus/AM');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (274,'Paulinha Paz','./Mulheres Palestrantes_files/08df93d.jpg','Salvador/BA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (275,'Preta Emmeline','./Mulheres Palestrantes_files/placeholder-female.jpg','Natal/RN');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (276,'Priscila Chagas','./Mulheres Palestrantes_files/0ecd5129c8defe57116e45a8078c2a68.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (277,'Rafaela Marques','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAimAAAAJDNmY2FjMWI5LWViODktNDhhZi04N2Y3LTA2MjQxNDUzMDM5YQ.jpg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (278,'Rafaella Cavalca','./Mulheres Palestrantes_files/placeholder-female.jpg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (279,'Raissa dos Santos Ferreira','./Mulheres Palestrantes_files/68328f099165564e758f8bd7c0a7ae05.jpeg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (280,'Raissa Klain Belchior','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAh_AAAAJDg3YTdhY2RhLWFlMTItNGJhYS04MmZjLWIzNzA0ZDZkODRmYw.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (281,'Raquel Camargo','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAlqAAAAJGZmYzk4Y2JmLTU4OWEtNDhmMS04MmU3LTdjNjFmMzM5MjZjYg.jpg','Belo Horizonte/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (282,'Raquel de Oliveira Santos Lira','./Mulheres Palestrantes_files/21d98c7ad075efd639ffbf0e50f9af35','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (283,'Raquel Prado','./Mulheres Palestrantes_files/cf9ab0b3894b990e19f4e85d6b62f34b.png','Curitiba/PR');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (284,'Raquel Preto','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (285,'Raquel Santachiara','./Mulheres Palestrantes_files/placeholder-female.jpg','Vila Velha/ES');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (286,'Rayanny Nunes','./Mulheres Palestrantes_files/placeholder-female.jpg','Natal/RN');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (287,'Reimy Solange Chagas','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (288,'Renata Machado Tárrio','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAMUAAAAJDUxZWE0OGQ2LTk0N2MtNDIwOS04MzBlLWNjM2RkNzIzOGJlMA.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (289,'Renata Masseroni','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (290,'Rebeca Bordini','./Mulheres Palestrantes_files/cb653395be591fe2387eddfb9319e4a3.jpeg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (291,'Rebeca Serpa','./Mulheres Palestrantes_files/acac3abd195659bf7d40086bae543427.jpeg','Osasco/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (292,'Rita Lino','./Mulheres Palestrantes_files/placeholder-female.jpg','Santos/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (293,'Robertta Mota','./Mulheres Palestrantes_files/placeholder-female.jpg','Fortaleza/CE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (294,'Ronaiza Cardoso','./Mulheres Palestrantes_files/f45e8318bf829e33e34c1b8b10e2cb1d.jpeg','Brasilia/DF');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (295,'Rosália Cipriano Oliveira','./Mulheres Palestrantes_files/AAMAAgDGAAwAAQAAAAAAAA8YAAAAJDg3YmI2ODkwLThlNjAtNGEyYy04MDUxLWJiODM1NTRkZTY3YQ.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (296,'Rosi Rodrigues','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (297,'Rosicléia Frasson','./Mulheres Palestrantes_files/6be2f94c93c57c403c131e6c80b6c356.jpeg','Joinville/SC');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (298,'Rute Faria','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAlyAAAAJDkzYzQ4MmMzLWNiYWItNDUzNC05YjA5LTU3ZGQ3OTRkMzYxMA.jpg','Belo Horizonte/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (299,'Samanta Cicilia','./Mulheres Palestrantes_files/d0e2beb1970140f2b36a8aa334c068a8.jpeg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (300,'Samantha Rosa','./Mulheres Palestrantes_files/2932644','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (301,'Samira Almeida','https://storymax.me/images/samira_lowres.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (302,'Sandy Maciel','./Mulheres Palestrantes_files/6650913','Fortaleza/CE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (303,'Silvana Bahia','./Mulheres Palestrantes_files/destaque_1502386742SilvanaBahia.jpg','Rio de Janeiro/RJ');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (304,'Silvia Helena Rocha Campos','./Mulheres Palestrantes_files/92cb9418155e8ae0de2214fafc908a43.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (305,'Silvia Valadares','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (306,'Simone Amorim','./Mulheres Palestrantes_files/0d3d7d27f9da8e0f1d2b69c626c9b4cc.jpeg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (307,'Simone Pittner','./Mulheres Palestrantes_files/9ac1f87ee020a87404cc22a3185966b1.jpeg','Florianópolis/SC e São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (308,'Soraia Lima','./Mulheres Palestrantes_files/6z7rU3yQ_400x400.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (309,'Stella Dauer','./Mulheres Palestrantes_files/07bab57.jpg','São Bernardo do Campo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (310,'Suzana Bueno','./Mulheres Palestrantes_files/AAEAAQAAAAAAAA29AAAAJDBiMjY0ZjkxLTBhMDUtNDg3NC04ZmNlLTU4MmQyNjRjZGJlYQ.jpg','Campinas/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (311,'Suzana Cohen','./Mulheres Palestrantes_files/placeholder-female.jpg','Belo Horizonte/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (312,'Tais Oliveira','./Mulheres Palestrantes_files/placeholder-female.jpg','Guarulhos/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (313,'Talita Lombardi','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (314,'Talita Pagani','./Mulheres Palestrantes_files/7b6f40fb2885d5c45f5f676df4bab5fb.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (315,'Talita Rossari','./Mulheres Palestrantes_files/dd46d758ae021e8f78c9cd8cefef0c27.jpeg','Florianópolis/SC');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (316,'Tancicleide Gomes','./Mulheres Palestrantes_files/2ce3c115479dbae97ee681b28ffc6725.jpeg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (317,'Tatiana Assali','./Mulheres Palestrantes_files/3ed51c2d50a2549abbfd64875b4ff641','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (318,'Tatiana Lourenço','./Mulheres Palestrantes_files/c5bccef3550aecfec2f68c38626c0860','Fortaleza/CE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (319,'Tatiana Pezoa','./Mulheres Palestrantes_files/placeholder-female.jpg','Campinas/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (320,'Tatiana Tosi','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (321,'Tatiana Vargas Maia','./Mulheres Palestrantes_files/placeholder-female.jpg','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (322,'Tatiane Conceição Vergueiro','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (323,'Tatti Maeda','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAxBAAAAJDU3ODJiZjg5LTk1N2EtNGRmOS04YzNiLTg0ZGVjNWU1Njg3ZA.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (324,'Tayra Vasconcelos','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (325,'Thais Gentile','./Mulheres Palestrantes_files/placeholder-female.jpg','Belém/PA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (326,'Thais Godinho','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (327,'Thais Moura de Freitas','./Mulheres Palestrantes_files/placeholder-female.jpg','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (328,'Thais Souza','./Mulheres Palestrantes_files/placeholder-female.jpg','Salvador/BA');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (329,'Thaisa Mirely','./Mulheres Palestrantes_files/54cf6dffa00e7d9f58f44da987cf53e6','Recife/PE');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (330,'Thaise Saeter','./Mulheres Palestrantes_files/aef601b2a2eb44af917418e2ae9fa339','Porto Alegre/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (331,'Thalita Nick Pinheiro','./Mulheres Palestrantes_files/e4103d70005e648a639d33a287a8dc0d.jpeg','Belo Horizonte/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (332,'Thaty Moura','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (333,'Uafa Smaili','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (334,'Valéria Barros','./Mulheres Palestrantes_files/4bbf316b66f8a754e0f9cdf67254515d.jpeg','Goiânia/GO');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (335,'Vanessa Gonçalves Ferreira','./Mulheres Palestrantes_files/1ddbed5.jpg','Belo Horizonte/MG');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (336,'Vanessa Kukul','./Mulheres Palestrantes_files/1b874de.jpg','Caxias do Sul/RS');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (337,'Vanessa Me Tonini','./Mulheres Palestrantes_files/2401246468e994e03713d5b83c16adaa.jpeg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (338,'Vanessa Queiroz','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAuwAAAAJGFkZjQ4ODBhLWMwY2UtNDg1MC04MTI5LTk2NzI1ODkwYzkyYQ.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (339,'Vanessa Rocha','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (340,'Vera Cristina de Moraes','./Mulheres Palestrantes_files/AAEAAQAAAAAAAAGDAAAAJDhmOGRhMjExLWNkZGMtNDBhMy1hNmI4LWZjZjUwNTRlMWE4NQ.jpg','Londrina/PR');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (341,'Vivian Vianna','./Mulheres Palestrantes_files/AAEAAQAAAAAAAATqAAAAJGQ2ZDgyN2FkLThkYmItNDBiOC05YzI3LWU4Mzk0ZmQyNzZjZA.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (342,'Viviane Vilella','./Mulheres Palestrantes_files/placeholder-female.jpg','São Paulo/SP');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (343,'Yanne Moreira','./Mulheres Palestrantes_files/e8922e930f20a9daa1e0a5169235ba4e.jpeg','Curitiba/PR');
INSERT INTO mytable(FIELD1,Nome,Foto,Localização) VALUES (344,'Yasodara Córdova','./Mulheres Palestrantes_files/7e089e6db99186280cfe1bbd1a80117c.png','São Paulo/SP');
