"temas"
"{Games,Tecnologia,Web,Conteúdo,""Rádio e TV"",""Edição de Vídeos""}"
"{Comunicação,""produção audiovisual"",""estudos de gênero""}"
"{""Comunicação e cibercultura"",""teorias da ficção-científica e imaginário tecnológico"",subculturas,""etnografia virtual"",""metodologias de pesquisa online"",""padrões de consumo na web"",cenas,fandoms,gêneros,""plataformas de música online"",""cultura pop""}"
"{""UX Design"",Front-end,Rails,""Web Design"",""Design thinking"",Leadership,""Creative process"",Empreendedorismo}"
"{""Gestão de Projetos"",Cocriação}"
"{Publicidade}"
"{""Desenvolvimento web"",UX,""Métodos Ágeis"",""Data Science"",""Comunicação e Informação"",Educação,""Ensino e Pesquisa""}"
"{""Social Media"",""Marketing digital"",Jornalismo,Planejamento,""Comportamento do consumidor"",Conteúdo}"
"{""Segurança da Informação"",Linux,""Shell Script""}"
"{Comunicação,Networking,Marketing,Inovação,Empreendedorismo,""Mídias Sociais""}"
"{Google,Cloud,Java,""App Engine"",Lean,Startups,Machismo,Diversidade}"
"{""Social Media"",""SAC 2.0"",Relacionamento}"
"{""Desenvolvimento Front e Back-end"",CakePHP3,Programação,Rails4,Laravel5}"
"{""UX Design"",Front-end,JavaScript,Rails,Agile,""Software Development""}"
"{Front-end,""UI Design"",""Web Design""}"
"{""Economia Colaborativa"",UX,HCI,""Desenho de Serviços"",""Mulheres na Tecnologia""}"
"{Android,Kotlin,""Data Science"",""Big Data"",NoSQL,Python,""Mulheres na Tecnologia""}"
"{""Live Games"",Teatro,""Gestão de Projetos"",""Game Design""}"
"{""Analista de TI"",Educadora,Blogueira,""Evangelizadora Joomla""}"
"{""Desenvolvimento Back-end"",""Mulheres na Computação"",Agile,Startups}"
"{""Gestão de Conteúdo"",Métricas,""Marketing Digital""}"
"{Planejamento,Pesquisa}"
"{Empreendedorismo,""Marketing Digital"",Negócios}"
"{Empreendedorismo,""Desenvolvimento de Produto"",Design,Mentoria}"
"{Monetização,Growth,""Análise de Negócios"",""Planejamento Estratégico"",""Gestão de Projetos""}"
"{JavaScript,""Programação Funcional"",""Desenvolvimento de Jogos"",Web}"
"{""marketing e comunicação digital"",""economia criativa"",""economia colaborativa"",hackschooling,""movimento maker"",""design thinking aplicado a planejamento de comunicação""}"
"{Python,Arduino,""Mulheres na Tecnologia e Ciência"",""Lógica de Programação""}"
"{unix,infraestrutura}"
"{Edutech,Design}"
"{Android,Python,""Mineração/Análise de dados"",Grafos,Comunidades,""Mulheres na Computação""}"
"{""Direito digital"",""negócios digitais""}"
"{""Varejo Digital"",""Atendimento ao Cliente"",""SAC 2.0"",""Projetos Digitais"",""Inovação Social"",Feminismo,""Gestão de Equipes"",""Branding Digital""}"
"{Empreendedorismo,""Marketing Digital"",""Criação de conteúdo"",""Pitch Training"",""Financiamento Coletivo""}"
"{""Computação em Nuvem"",""Sistemas Distribuídos"",Back-End}"
"{Startups,Front-end,""Outreachy program"",""Software livre""}"
"{Python,""Machine Learning"",""Data Science"",""Open Source"",Ruby,Rails,Front-end,""Software Development""}"
"{Empreendedorismo,RH,""Treinamento e consultoria empresarial"",""Desenvolvimento de equipes"",""Modelagem de negócio"",""Organização de fluxos e processos"",""Pesquisas empresariais e organizacionais""}"
"{""Mobile Advertising"",Diversidade,Inclusão,""LGBT Rights""}"
"{Propaganda}"
"{""Desenho de Moda"",""Comidas Orgânicas""}"
"{Front-end,Comunidade,Acessibilidade}"
"{""Product Management"",Agile,Scrum,Lean}"
"{""Machine Learning"",Python,Javascript,""Análise de Dados"",""Visualização de Dados"",R,""Agile Analytics""}"
"{Empreendedorismo,BigData,Comunidades,""Mulheres na Computação""}"
"{""Impressora 3D"",""negócios sociais""}"
"{Ruby,Rails}"
"{Coaching,Agilidade,""Agile Coach"",Liderança,Facilitação}"
"{WordPress,""Web Design"",Interatividade}"
"{""Evangelizadora Joomla"",""Web engineer"",""Consultora em FOSS""}"
"{""Desenvolvimento e participação das mulheres no mercado de games (impacto nacional e mundial)""}"
"{""Inbound PR"",Personas,""Relações Públicas Digitais"",""Inbound Marketing""}"
"{""Testes de Software"",Automação,""Qualidade de software""}"
"{""Varejo de moda"",""Visual Merchandasing"",""Criatividade e inovação"",Educação}"
"{Canvas}"
"{""Inteligência Artificial"",""Mineração de dados"",Rails,R,""Machine Learning""}"
"{""Testes de Software"",Lean,Agile,Rails,Ruby,Cucumber}"
"{UX,""Engenharia de Software"",Eletrônica,""Gestão de Projetos""}"
"{""UX Design"",""Mulheres na Tecnologia""}"
"{Golang,Python,""Data Science"",Leadership}"
"{Angular,JS,""Fullstack Development"",""Segurança em Aplicações Web""}"
"{Front-end,""Web Design"",Wordpress,Design,UX}"
"{Empreendedorismo}"
"{Rails,Ruby,Back-end}"
"{""Product Management"",Leadership,""Growth Hacking"",Entrepreneurship,""Venture Capital"",Agile}"
"{""Negócios digitais"",Gastronomia}"
"{""economia compartilhada""}"
"{Conteúdo,SEO}"
"{""Liderança Feminina"",""Gênero & Inovação"",""Empreendedorismo Feminino"",""Gênero & Tecnologia""}"
"{Branding,UX,Startup,""Design Thinking"",""Web Design""}"
"{""Gestão de Projetos"",""Gestão de Pessoas"",Operações,Processos,Motivação,""Comunicação Interna"",""Inteligência Digital"",Atendimento}"
"{""Desenvolvimento Web"",""Mídias Sociais"",""Web Design"",""Social Media Design""}"
"{""Desenvolvimento de software"",Agilidade,""Entrega e integração contínua"",""Empoderamento feminino""}"
"{Empreendedorismo}"
"{Sexualidade,Feminismo,""Direitos Humanos"",""Questões de Gênero"",Maternidade,""Social Media"",Jornalismo}"
"{Finanças,Empreendedorismo,""Produção de Conteúdo""}"
"{Web,""Data on the Web"",""Open Data"",""Open Government"",""International Relations"",Feminismo}"
"{""Marketing Digital"",""Mídias Sociais"",PHP,Front-end}"
"{Back-End,""Front End"",""Analista SEO"",""Especialista em Joomla e Consultoria WEB""}"
"{""Análise de negócios"",""Modelagem de dados"",""Desenho de processos"",""Liderança de equipes""}"
"{Front-end,Back-end,Design,Mobile,""Controle de Versão""}"
"{Jornalismo,Empreendedorismo,""Conteúdo Digital"",""Conteúdo para marcas""}"
"{Design,Sustentabilidade,""Economia criativa""}"
"{Coaching,Liderança,Lean,""Agile Coach"",Agilidade,Facilitação}"
"{Atendimento,Motivação,Secretariado,""Etiqueta Empresarial""}"
"{Empreendedorismo}"
"{Coaching,Feminino}"
"{Empreendedorismo,Estratégia,Marketing}"
"{UX,Mobile,Front-end,""Software Livre"",Inovação,""Pesquisa Acadêmica"",Metodologias,""Alfabetização para Web"",""Inclusão Social"",Empreendedorismo,""Startups e Comunidades de Desenvolvimento"",Cloud,""Developer Tools""}"
"{""Comunicação Estratégica"",""Mídias Sociais"",""Gestão de Projetos"",Branding}"
"{""Estratégias de Facebook para campanhas internacionais""}"
"{VueJS,PWA,""Interfaces Interativas"",""Animação para Web"",Educação}"
"{Mobile,Android,Front-end,JavaScript,""Arte e tecnologia"",IoT}"
"{""Jornalismo Digital"",""Estratégia de Conteúdos"",""Redes Sociais"",""Digital Strategist""}"
"{""Sistemas Mobile Android"",""Segurança em Dispositivos Android""}"
"{""Engenharia de Software"",Ruby,Backend}"
"{Python,""Mulheres na Computação"",Chatbots}"
"{""Big Data"",""Data Science"",""Machine Learning""}"
"{Marketing,Comunicação,Negócios}"
"{Liderança,Empreendedorismo,""Mídias sociais""}"
"{Programação,Front-End,""Qualidade de Software""}"
"{UI/UX,Branding,""Design para startups"",""Design de experiência (multissensorial)""}"
"{Mobile,""Internet das Coisas"",""Requisitos de Software"",Empreendedorismo,""Sistemas Embarcados""}"
"{Empreendedorismo,""Comportamento do Consumidor"",""Mídias Sociais"",Tecnologia,""Marketing Digital"",BI}"
"{Javascript,d3.js}"
"{""Empreendedorismo Feminino"",""Inovação e Diversidade"",""Economia da Mulher"",Liderança,""Gênero nas Empresas""}"
"{""Gestão de Projetos"",SCRUM,""Lean Development""}"
"{""Projetos de TI para Marketing""}"
"{""Social Media"",Marketing,""Estratégias Comunicacionais"",""Relações Públicas"",""Marketing Digital""}"
"{Empreendedorismo,Inovação,Empoderamento,Negritude}"
"{""Desenvolvimento Web"",PHP,""Metodologias Ágeis"",Empreendedorismo,""Team Work""}"
"{""Inteligência Cultural"",""Éitca de Estética"",""Diversidade Brasileira"",""Processos Criativos"",""Inovação x Criatividade"",""Empoderamento Feminino"",Representatividade,""Cultura Negra""}"
"{""Financeiro e inovação""}"
"{""Martketing Digital"",Saúde,""Redes Sociais""}"
"{Educação,Tecnologia,Empreendedorismo,""Gestão do conhecimento""}"
"{""Empoderamento Feminino"",Tecnologia,""Movimento Maker"",""Indústria 4.0"",Eletrônica}"
"{""Desenvolvimento Android"",""Material Design"",""Engenharia de Software"",Comunidades}"
"{""Desenvolvimento Web e mobile""}"
"{Neuromarketing,Neurobusiness,""Neurociência do Consumo"",""Linguagem Corporal"",""Detecção de Mentiras""}"
"{""Games Inteligentes"",""Inovação na Educação""}"
"{Marketing,Inovação,Palestras,Empreendedorismo,""Mentoria e Oficinas com Metodologia CEFE Internacional""}"
"{Back-end,suporte}"
"{Empreendedorismo,Produtividade,""Gestão do Tempo"",""Organização Empresarial"",Qualidade}"
"{Cyberfeminismo,""Redes Sociais"",""Empoderamento da Mulher""}"
"{""Live Marketing"",""Campanhas Integradas"",""Planejamento de Produção"",Branding,Conteúdo}"
"{Empreendedorismo}"
"{Empreendedorismo}"
"{Front-End,UX,""Desenvolvimento Web e Mobile"",Empreendedorismo,Saúde}"
"{""Open Data"",""Open Government"",E-government,Hackativismo}"
"{""Acessibilidade Web"",Design,Quadrinhos,""Governo Eletrônico""}"
"{""Operações e Negócios digitais""}"
"{""Marketing Digital"",LinkedIn}"
"{""Mídias sociais""}"
"{Branding,""Comunicação Empresarial"",Mídia}"
"{""Desenvolvimento Web"",""Desenvolvimento de Software"",Feminismo,Ruby,Rails}"
"{""Programação funcional"",""Mulheres no mercado de TI"",""Qualidade de código""}"
"{Conteúdo,""Marketing Digital"",""Mídias Sociais"",""Escrita Criativa""}"
"{""Programação OO"",""Educação Informática: com foco na geração Y e suas diferenças entre a X e a Z""}"
"{Python,""Diversidade e Impacto social"",Comunicação,Educação}"
"{""Economia criativa""}"
"{Mecatrônica,""Sistemas Embarcados"",Robótica,Programação}"
"{Inovação,Propósito,Estratégia,Criação,""Design Thinking"",Comunicação,Tendências}"
"{Internacionalização,Empreendedorismo}"
"{Tecnologia,Videogames,""Relações Públicas""}"
"{Auto-desenvolvimento,""Risco de Crédito"",""Risco Operacional"",""Empreendedorismo Digital"",""Inovação no Mundo de Crédito"",""Prevenção a Fraudes"",""Motivação Feminina""}"
"{""Marketing Digital"",""Digital e Infância"",""Estratégia de Negócios""}"
"{""Design Thinking"",Inovação,Conectividade,""Processos Criativos""}"
"{SEO,Conteúdo,Facebook,""Empreendedorismo Digital""}"
"{Empreendedorismo,Inovação,""Negócio Social"",Startups,""Empreender na área de tecnologia"",""Empreender na área de Educação"",""Estratégia de negócios para Microempreendedores"",""Gestão de Projetos em TI"",""Canvas e Modelo de Negócio""}"
"{""Gênero e tecnologia"",Hackativismo,""Mobilidade urbana"",""Transporte e gênero"",""Assédio no ambiente de trabalho""}"
"{""Direito digital"",Bitcoin}"
"{""Front-End Development""}"
"{""Educação Financeira"",Investimentos,""Consumo Consciente""}"
"{""Assessoria de Imprensa"",""Jornalismo Digital""}"
"{""Desenvolvimento de Software"",""Machine Learning"",TDD,""Testes Automatizados"",Docker,Agile}"
"{""Social CRM"",Conteúdo,Monitoramento,""Gestão de Crises"",Pesquisa}"
"{TI,""Liderança Feminina"",Governança,LSS}"
"{""Jogos educacionais"",Gamificação,""Game design"",""Educação e tecnologia""}"
"{Startups,Empreendedorismo,Moda,Nordeste,Design}"
"{""Product Management"",""Negócios Sociais"",""Empoderamento Feminino""}"
"{Comunicação,Sustentabilidade,""Assessoria de Imprensa"",""Assessoria Digital"",""Comunicação Corporativa""}"
"{""Desenvolvimento Web"",Mobile,Tecnologia,""Desenvolvimento de Software""}"
"{TI,""Desenvolvimento de Software"",""Empoderamento Feminino"",Diversidade,Transexualidade,""Mudar o mundo através da tecnologia""}"
"{UX,Design,Games}"
"{""Data Science"",""Open Source"",Python,""Dados Abertos""}"
"{Empreendedorismo}"
"{""Negócios digitais""}"
"{iOS,""Desenvolvimento web""}"
"{""Desenvolvimento Web com PHP"",""Zend Framework 2"",Doctrine}"
"{""Cinema LGBT"",""Cinema Indiano"",Criação,Mídia}"
"{""Desenvolvimento WEB"",""Mulheres na Tecnologia"",Empreendedorismo,Educação}"
"{Gamificação,""Mídias Digitais"",Videogames,Arte}"
"{""Saúde Pública"",Drogas,""Educação em Saúde"",""Atenção Básica""}"
"{Startups,Empreendedorismo,Moda,Nordeste}"
"{Mobile}"
"{""TI verde"",""Software livre"",""Gerenciamento de TI"",""Banco de Dados""}"
"{""Desenvolvimento de Software"",Agilidade,""Arquitetura de Software"",DevOps,""Software livre""}"
"{UX,Acessibilidade}"
"{""Redes Sociais"",""Comunicação Digital"",Marketing}"
"{Design,Branding,""Comunicação Visual""}"
"{Planejamento,Feminismo,Conteúdo,Podcast}"
"{Empreendedorismo,""Mulheres na TI"",Programação,""Segurança da Informação"",Inovação}"
"{Design,""Web Design"",""Desenvolvimento Web"",Marketing,Empreendedorismo}"
"{""Gênero e Tecnologia"",""Gamificação e Jogos"",""Engenharia de Software"",""Metodologia Científica (para quem não gosta de metodologia científica)""}"
"{""Teoria da Computação"",Lógica,Matemática,""Divulgação Científica"",""Mulheres na Computação""}"
"{""Publicidade online""}"
"{Transmidia}"
"{""Redes Sociais"",""Fotografia de Parto"",""Captação de Doadores de Sangue""}"
"{""UX Design"",Mobile,""Pesquisa Acadêmica"",E-government}"
"{Front-end,Javascript,""HTML5 Canvas"",""Animação para Web e Interfaces Interativas""}"
"{Marca,Inovação,Diferenciação}"
"{""História em Quadrinhos"",Feminino,Ilustrações,Roteiro}"
"{""Desenvolvimento Web""}"
"{Empreendedorismo}"
"{""Varejo de Moda"",""Negócios da Moda"",""Produção de Moda"",""Visual Merchandising"",""Experiências do Consumo""}"
"{Empreendedorismo}"
"{""Software livre"",""Desenvolvimento de Software"",Educação,Sustentabilidade}"
"{""Marketing Digital"",""Social Media"",Planejamento,""Brand Persona"",Métricas,""Gestão de Crise""}"
"{Design,Ilustração,""Comunicação Visual"",""Produção Gráfica""}"
"{Python,Comunidade,""Data Analysis"",Django}"
"{""Ciência de Dados"",""Big Data""}"
"{Programação,Web,Mobile,""Testes Automatizados"",Back-end,.NET,Xamarin,Ionic}"
"{Empreendedorismo,Programação,C#,Microsoft,""App Inventor"",""Windows Phone"",Engenharia,Arduino,""Intel Galileo"",Motivação,Inspiração,Inovação,""Metodologias de Gerenciamento de Tempo e Ações ""}"
"{Python,Ensino,""Software Livre"",""Jornalismo Cidadão"",""Mulheres na TI""}"
"{Conteúdo,Marketing,Jornalismo,""Mídias Sociais""}"
"{Ecommerce,Inovação,Hobby,Empreendedorismo}"
"{""Facebook Marketing""}"
"{Neuromarketing,""Links Patrocinados"",""Online Advertising"",""Social Media""}"
"{Monitoramento,""Auditoria de Imagens"",Tendências}"
"{""Conteúdo para Startups"",""Marketing Digital"",Jornalismo,Comunicação,""Mídias Sociais""}"
"{""Desenvolvimento Front e Back-end"",JavaScript,""Mobile Híbrido"",Java,Sencha,Escritora}"
"{""Mídias sociais""}"
"{Arquitetura,""Responsabilidade Social""}"
"{Empreendedorismo,RH}"
"{Conteúdo,""Redes Sociais"",Blogs,Internet,""Mercado no interior de SP""}"
"{Testes,Automação,""Qualidade de Software"",Comunidades,""Acessibilidade Web"",usabilidade}"
"{Comunicação,""Relações Públicas"",Social,Digital,Conteúdo,Eventos,Ideias}"
"{DevOps,Java,""Automação de infraestrutura"",""Mulheres na TI""}"
"{Transmidia}"
"{""Recursos Humanos"",Refugiados,""Empreendedorismo Social""}"
"{Conteúdo,RP,H2H,Empreendedorismo,""Negócios Sociais""}"
"{""Ensino de Programação para crianças e jovens"",""Empoderamento Feminino"",Diversidade,""Cultura Maker"",""Empoderamento através da tecnologia"",Arduino,""Robótica Educacional"",""Internet das Coisas"",""Educação e Tecnologia""}"
"{""Mulheres na Tecnologia""}"
"{""FrontEnd Development"",UI/UX,""Inteligência Artificial""}"
"{Crowdsourcing,Crowdfunding}"
"{Python,""Image Processing"",""Medical Image Processing"",""Machine Learning"",""Data Science"",""Open Source"",Education,Empowerment}"
"{Empreendedorismo,E-commerce}"
"{""Desenvolvimento Web"",""Aprendendo Mobile""}"
"{""Preconceito Racial"",Feminismo,Fotografia}"
"{Design,UX,Wordpress,Costura}"
"{Cibercultura,""Mídias Sociais"",""Comportamento do Consumidor Online"",""Relacionamentos Virtuais"",""Pesquisa Qualitativa""}"
"{""Empreendedorismo Social"",Turismo,Sustentabilidade}"
"{""Impacto da tecnologia e das novas mídias na comunicação e na vida profissional""}"
"{""Negócios sociais"",""Inovação social""}"
"{""Empreendedorismo Social""}"
"{Front-end,Webdesign,UX}"
"{""Tecnologias Assistivas"",Jogos,Educação,Inovação}"
"{""Publicidade e Propaganda"",Empreendedorismo,""Marketing Digital"",""Mídias Sociais"",""Planejamento Estratégico e de Comunicação""}"
"{Permacultura,Sustentabilidade}"
"{""Cervejas Artesanais"",""Fabricação de Cerveja"",""Mercado Cervejeiro""}"
"{""Pesquisa em Profundidade sobre o Brasil"",""Planejamento Estratégico"",Etnografia}"
"{Facilitação,Empreendedorismo,""Engenharia de Produção"",Lean,""Inception Enxuta"",""Analista de Negócios"",""Metodologia Ágil""}"
"{Empreendedorismo,Criatividade,""Produção Digital"",Publicidade}"
"{""Mobilidade Ativa"",""Planejamento de Mobilidade"",""Mobilidade Urbana""}"
"{""Social Media"",""Alfabetização para Web"",Games,""Marketing digital"",""Conteúdo Digital"",""Métricas para redes sociais"",""como salvar gatinhos =P""}"
"{""Programação (Java)"",UML}"
"{Empreendedorismo}"
"{Marketing,""Comunicação Digital""}"
"{""Marketing Digital"",SEO,SEM,Branding}"
"{""Redes Sociais"",""Economia Local"",Juventude,NetAtivismo}"
"{Feminismo,LifeHacking,""Comunicação e Questões de Gênero""}"
"{Moda,""Economia Criativa"",""Cidades inteligentes e humanizadas""}"
"{""Mobilização Digital"",""Cobertura Digital de Eventos"",""Articulação Política"",""Software Livre"",""Relações Públicas""}"
"{""Economia Criativa""}"
"{Publicidade,""Relações Públicas"",""Consumo Consciente"",""Comunicação Face a Face"",""Responsabilidade Social""}"
"{Marketing,""Engajamento Cívico"",""Mulheres na Tecnologia"",""Ciências Sociais""}"
"{SEO,usabilidade,""Marketing digital""}"
"{Publicidade,Propaganda,Cannes,Prêmios,""Direção de Arte"",""Mercado de Trabalho""}"
"{Empreendedorismo,""Qualidade de Software"",""Engenharia de Software"",Processos,Requisitos,Testes}"
"{""Levantamento de Requisitos"",""Engenharia de Software"",""Desenvolvimento de Software"",""Tecnologia educacional"",""Software Livre"",""Governança da Internet"",""Mulheres na tecnologia e/ou na engenharia"",Educação}"
"{""Design de Negócios"",""Design de Serviços"",""Design Thinking"",""Comunicação Institucional"",Planejamento,""Comportamento do Consumidor""}"
"{Agilidade,""Gestão de Projetos"",""Transformação Digital"",""Governo Digital""}"
"{Empreendedorismo}"
"{""Téc de suporte""}"
"{""Imagem Pessoal"",""Imagem Profissional""}"
"{""Análise de mídias sociais"",""Web Designer"",Programação}"
"{""Pesquisa de Mercado"",""Inteligência de Mercado"",""Comportamento do consumidor""}"
"{""Google AdWords"",""Google Meu Negócio"",""Google Analytics""}"
"{Colaboração,""Economia Colaborativa""}"
"{Moda,Empreendedorismo,Tendências}"
"{Front-End,Testes,Ruby}"
"{Front-end,UX}"
"{""Desenvolvimento de software"",Python,AngularJS,JavaScript,C#}"
"{Empreendedorismo}"
"{""Marketing Digital"",Planejamento,""Comunicação 360""}"
"{Empreendedorismo}"
"{Agile,""Análise de Negócios"",""Empoderamento Feminino""}"
"{""Análise de Mídia"",Conteúdo,Blogs,Jornalismo}"
"{Finanças,""Negócios Digitais""}"
"{""Desenvolvimento de Software"",Ruby,Rails,Javascript,AngularJS}"
"{Empreendedorismo,Startups,Motivação,Conteúdo,BizDev}"
"{""Comunicação Digital"",""Mídias Sociais"",""Open Data"",Empreendedorismo,""Facilitação de Eventos Colaborativos"",""Metodologias de Conversação"",Blogs,Monetização}"
"{Empreendedorismo,""Políticas Públicas"",""Inovação na Educação""}"
"{""UX Design"",""UI Design"",Usabilidade,Prototipação,""App Design""}"
"{""Leis para startups""}"
"{""Design Thinking"",""Empreendedorismo Social""}"
"{Empreendedorismo}"
"{""Psicologia Intercultural"",Imigração,Interculturalidade,Multiculturalismo,""Famílias Culturalmente Diversas""}"
"{""Marketing Digital"",""Marketing de Conteúdo"",Comunicação,Semiótica}"
"{Empreendedorismo}"
"{""Desenvolvimento de software"",Python,Javascript,React}"
"{Jornalismo,Blogs,Igrejas,MPB}"
"{Empreendedorismo,Inovação,Programação}"
"{Valuation,Investimento,Internacionalização}"
"{Web,""Programadora PHP"",Git,Laravel}"
"{""Curadoria de Conteúdo"",""Social Content"",""Jornalismo Digital""}"
"{Empreendedorismo}"
"{""Desenvolvimento Front e Back-end"",Java,Agile,""Desenvolvimento Web""}"
"{""Mídias Sociais"",Monitoramento,""Mensuração de Dados"",Curadoria,""Produção de Conteúdo""}"
"{Testes,Agilidade,Automação,Lean,""Continuos Delivery"",DevOps,""Qualidade de Software"",Comunidades}"
"{UX,Liderança,Design,Educação}"
"{Empreendedorismo,Inovação,""Tecnologia em Educação"",Comunicação,Literatura,Leitura}"
"{""Qualidade de Software"",""Teste de Software"",""Lua Lang"",""Mulheres na Tecnologia"",Empreendedorismo,""Gerência de Processo"",Gamificação}"
"{Inovação,Diversidade,Makerspace}"
"{""Violência Doméstica"",""Empoderamento Feminino"",""Direitos da Criança e do Adolescente"",""Relações Homoafetivas"",""Guarda Compartilhada"",""Casamentos Homoafetivos"",""Adoção por casais do mesmo sexo"",""Medidas Protetivas"",Cidadania,""Direitos e Deveres Básicos"",Educação}"
"{Empreendedorismo}"
"{""Desenvolvimento Web"",CSS,""Java Script""}"
"{""Desenvolvimento de Software"",Agilidade,""Gestão de Projetos"",""Gestão de Processos"",Empreendedorismo}"
"{""Monitoramento de Mídias Sociais"",""Branded Content"",""Jornalismo Digital"",""Social Journalism""}"
"{Resenhas,Gadgets,""Canais no YouTube""}"
"{SAC,Relacionamento,""Desenvolvimento TI"",Games}"
"{""Comunicação Digital"",""Trend Hunting"",""Novas Mídias""}"
"{""Marketing Digital"",""Relações Públicas"",Planejamento,Blogs,""Comunicação Empresarial""}"
"{""Vendas para negócios digitais""}"
"{UX,front-end,""acessibilidade Web"",usabilidade,carreira,""vida acadêmica"",""mercado de trabalho"",""engenharia de software""}"
"{Development,Backend,Python,Git,Django}"
"{""Lógica de Programação"",""App Inventor"",Scratch,PHP,Python,Javascript,jQuery,""Desenvolvimento Web"",""Design de Jogos Educativos"",""Inovação em Educação"",Gamificação,""Mobile Learning"",""Design Participativo""}"
"{""Investimento Responsável"",""Finanças Sustentáveis""}"
"{Branding,""Gestão de Negócios"",Design,Storytelling}"
"{E-commerce}"
"{Netnografia}"
"{Feminismo,""Teoria Feminista"",""Questões de Gênero"",""Política Contemporânea"",""Relações Internacionais"",Nacionalismo,Identidades}"
"{""Jornalismo Digital"",Política,Advocacy,Social}"
"{""Marketing de Atendimento"",Conteúdo,Pessoal}"
"{""Assessocia comercial para blogs""}"
"{""Social Mídia"",Conteúdo}"
"{""Produtividade Pessoal"",Organização,Coaching}"
"{Computação}"
"{""Mídias Sociais"",Planejamento,Monitoramento}"
"{Mobile,""Pesquisa Acadêmica"",""Software livre""}"
"{Comunicação,""Economia Criativa ""}"
"{Development,Backend,JavaScript,Qualidade,Agilidade}"
"{Inteligência,Planejamento,""Gestão de Crise"",""Gestão de Equipe""}"
"{SEO,""UX Design"",""Mídias Sociais""}"
"{Programação,PHP,""Alfabetização Para Web"",""Mercado de Trabalho"",""Software Livre"",""Mulheres na Tecnologia"",Mozilla}"
"{""Marketing Digital"",""Mídias Sociais"",Portais,""Retorno no Investimento em Marketing"",""Inbound Marketing"",""Email Marketing"",""Plano de Comunicação Integrada""}"
"{""Inteligência Coletiva"",Empreendedorismo,""Negócios Sociais"",""Gestão de Pessoas"",Liderança,Inovação}"
"{""Métodos Ágeis"",Angular2,Marialab,""Acessibilidade Web"",FrontEnd,Git,Magento}"
"{Empreendedorismo,Design,Branding,Ilustração}"
"{Monetização,Internacionalização}"
"{Inovação,Conteúdo,""Marketing para Startup"",Empreendedorismo,Tecnologia,""Jornalismo Online""}"
"{""Marketing de Conteúdo"",Empreendedorismo,""Marketing Digital"",WordPress}"
"{E-commerce}"
"{Wordpress,FrontEnd,Design,""Interface Design"",""UX Design""}"
"{Web,""Semantic Web"",Data,""Open Data"",Datavis,""UX Design""}"
